### PR TITLE
Builtins

### LINKED ISSUE #331: Undefined built-in function error message is missing the built-in name
For example:

```
torin:~$ opa run
OPA 0.4.10-dev (commit 48de325, built at 2017-05-19T21:01:54Z)

Run 'help' to see a list of commands.

> p(1)
1 error occurred: 1:1: rego_type_error: undefined built-in function
```

It would be nice if the error message included the bad built-in name (`p` above).

This should only require a small change in ast/check.go.

Desired error:

```
 rego_type_error: undefined built-in function 'p'
```

### PR DESCRIPTION
**Pull request by mmussomele**
Resolves #331, #326 and #309, along with a bug I found while reading through the code.

### CODE REVIEW

**Comment by mmussomele** [comment]
FWIW, I felt the string buitins could be in one commit together, but if it's preferable I can break them up.

File: topdown/topdown_test.go [hunk 1]
```diff
@@ -990,6 +990,12 @@ func TestTopDownAggregates(t *testing.T) {
 		{"max set", []string{`p = x { max({1, 2, 3, 4}, x) }`}, "4"},
 		{"max virtual", []string{`p[x] { max([y | q[y]], x) }`, `q[x] { a[_] = x }`}, "[4]"},
 		{"max virtual set", []string{`p = x { max(q, x) }`, `q[x] { a[_] = x }`}, "4"},
+		{"min", []string{`p[x] { min([1, 2, 3, 4], x) }`}, "[1]"},
+		{"min dups", []string{`p[x] { min([1, 2, 3, 4], x) }`}, "[1]"},
```
Comment (tsandall) [inline topdown/topdown_test.go]: Nit: test input is same as above.

**Comment by mmussomele** [comment]
Should be fixed now
