### PR TITLE
server: Abort write transaction when parsing fails

### LINKED ISSUE #1478: Server leaks write transaction if parse fails on update
The server is not aborting the write transaction when PUT /v1/policies fails due to an malformed or empty policy. The server is then unable to process further policy updates because of the open write transaction.

This is causing https://github.com/open-policy-agent/kube-mgmt/issues/41.

EDIT: This will get fixed in the next day and we'll cut a v0.11.1 release containing the fix.

### PR DESCRIPTION
**Pull request by tsandall**
The server was leaking the write transaction when parsing failed which
caused subsequent updates to block. In future we should refactor the
handler implementations to avoid having to manually abort on each
error path.

Fixes #1478

Signed-off-by: Torin Sandall <torinsandall@gmail.com>

### CODE REVIEW

File: server/server_test.go [hunk 1]
```diff
@@ -1696,6 +1696,24 @@ func TestPoliciesPutV1ParseError(t *testing.T) {
 	if name.Compare(ast.String("test")) != 0 {
 		t.Fatalf("Expected name ot equal test but got: %v", name)
 	}
+
+	req = newReqV1(http.MethodPut, "/policies/test", ``)
+	f.reset()
+	f.server.Handler.ServeHTTP(f.recorder, req)
+	if f.recorder.Code != 400 {
+		t.Fatalf("Expected ok but got %v", f.recorder)
```
Comment (patrick-east) [inline server/server_test.go]: Should this error be `Expected error but got %v` ?

Comment (tsandall) [reply server/server_test.go]: Whoops. Copy pasta. Will fix.
