### PR TITLE
wasm/sdk: add benchmarks

### LINKED ISSUE #2535: WASM benchmarks
We don't currently have a set of benchmarks for the WASM generated policies or for their builtins. Having this would make it much easier to track progress over time and detect any regressions.

We would probably want to have a set of benchmark tests similar to benchmarks defined in `./topdown`, but will need a framework to run them and process results.

### PR DESCRIPTION
**Pull request by srenatus**
This is porting some of the existing topdown tests -- but run with the WASM SDK.

I've come to believe that whatever memory usage data we're collecting there is probably bogus: too many of my runs yield
```
1597 B/op	      41 allocs/op
```
regardless of the input size. I'd think that the problem lies in the boundary crossing to cgo-land, but I have yet to find a source for that.

That aside, disabling the allocation reporting, and gathering benchmark data for the run _times_ is probably already useful, so let's go with that.

-----

Fixes #2535.

### CODE REVIEW

File: internal/wasm/sdk/opa/opa_bench_test.go [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+		})
+	}
+}
+
+func BenchmarkWASMVirtualDocs(b *testing.B) {
+	for _, kv := range []struct{ total, hit int }{
+		{1, 1},
+		{10, 1},
+		{100, 1},
+		{1000, 1},
```
Comment (srenatus) [inline internal/wasm/sdk/opa/opa_bench_test.go:117]: I've been adding a few data points in between 100 and 1000 to glimpse at the line graph:

Screenshot 2021-01-27 at 17 28 42

```
goos: darwin
goarch: amd64
pkg: github.com/open-policy-agent/opa/internal/wasm/sdk/opa
BenchmarkWASMVirtualDocs/total=1/hit=1-16         	   60504	     20041 ns/op
BenchmarkWASMVirtualDocs/total=10/hit=1-16        	   51378	     21870 ns/op
BenchmarkWASMVirtualDocs/total=100/hit=1-16       	   33804	     36900 ns/op
BenchmarkWASMVirtualDocs/total=200/hit=1-16       	   20919	     55119 ns/op
BenchmarkWASMVirtualDocs/total=300/hit=1-16       	   15438	     76811 ns/op
BenchmarkWASMVirtualDocs/total=500/hit=1-16       	   10000	    116501 ns/op
BenchmarkWASMVirtualDocs/total=750/hit=1-16       	    7716	    159633 ns/op
BenchmarkWASMVirtualDocs/total=1000/hit=1-16      	    5395	    195809 ns/op
PASS
ok  	github.com/open-policy-agent/opa/internal/wasm/sdk/opa	23.376s
```

File: internal/wasm/sdk/opa/opa_bench_test.go [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+)
+
+func BenchmarkWASMArrayIteration(b *testing.B) {
+	sizes := []int{10, 100, 1000, 10000}
+	for _, n := range sizes {
+		b.Run(fmt.Sprint(n), func(b *testing.B) {
+			benchmarkIteration(b, n, test.ArrayIterationBenchmarkModule(n))
+		})
+	}
+}
```
Comment (srenatus) [inline internal/wasm/sdk/opa/opa_bench_test.go:20]:
```
BenchmarkWASMArrayIteration/10-16                  63955             20077 ns/op
BenchmarkWASMArrayIteration/100-16                 60627             19055 ns/op
BenchmarkWASMArrayIteration/1000-16                63928             18837 ns/op
BenchmarkWASMArrayIteration/10000-16               63242             18745 ns/op
```

This still puzzles me. It's practically flat. This isn't what I had expected.

File: internal/wasm/sdk/opa/opa_bench_test.go (hunk 1 above)
Comment (srenatus) [reply internal/wasm/sdk/opa/opa_bench_test.go:115]: https://github.com/cep21/benchdraw was the first thing I've found that seemed like it required very little effort to use 😄

File: internal/wasm/sdk/internal/wasm/util.go [hunk 3]
```diff
@@ -4,12 +4,13 @@
 
 package wasm
 
-const wasmPageSize = 65535
+// PageSize represents the WASM page size in bytes.
+const PageSize = 65535
```
Comment (srenatus) [inline internal/wasm/sdk/internal/wasm/util.go:8]: ℹ️ Unrelated, but I wanted to avoid the constant in other places.

File: internal/wasm/sdk/opa/opa_bench_test.go (hunk 2 above)
Comment (srenatus) [reply internal/wasm/sdk/opa/opa_bench_test.go]: Resolved: this will change when #3112 is merged.

**Comment by srenatus** [comment]
I'll rebase this and mark it RFR when #3112 is in.

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/opa/pull/3103/checks?check_run_id=1817100224#step:3:6225 👈 example run on CI

File: internal/wasm/sdk/opa/opa_bench_test.go [hunk 4]
```diff
@@ -0,0 +1,194 @@
...
+		{100, 1},
+		{1000, 1},
+		{10, 10},
+		{100, 10},
+		{1000, 10},
+		{100, 100},
+		{1000, 100},
+		{1000, 1000},
+	} {
+		b.Run(fmt.Sprintf("total=%d/hit=%d", kv.total, kv.hit), func(b *testing.B) {
```
Comment (tsandall) [inline internal/wasm/sdk/opa/opa_bench_test.go:163]: I _much_ prefer this notation to the `NxM` style used in the topdown tests...I can never remember what the topdown test names refer to without looking at the implementation 😅

**Review by tsandall — APPROVED** [review]
LGTM. 2.5-3x speedup for the iteration benchmarks and similar for the non-indexed virtual doc benchmarks isn't too bad. Also, the virtual doc benchmark with `total=1000` and `hits=10` is <1ms which is good. As a baseline this is encouraging; there's lots of room for optimization.

File: internal/wasm/sdk/opa/opa_bench_test.go (hunk 4 above)
Comment (srenatus) [reply internal/wasm/sdk/opa/opa_bench_test.go:163]: We could fix the other ones to use this style, we'd only loose one comparison in the bench diff stuff we have (due to the renamed tests).

**Comment by srenatus** [comment]
I'm about to squash and merge this. I'm uncertain about whether the "array/set/object iteration" checks really benchmark said iteration, or the performance of `numbers.range()`, but we can take a look at that some other day. The virtual docs benchmark should be doing what's advertised.
