### PR TITLE
topdown: introduce queryIDFactory for unique queryIDs

### LINKED ISSUE #707: topdown.eval query IDs are not unique
The query IDs generated during evaluation are not unique which results in [incorrect support rule names being generated during partial eval of negated expressions](https://github.com/open-policy-agent/opa/pull/704).

topdown.eval should be modified to include a query ID factory that generates unique IDs for all child/closure queries.

something like...

```go
func (f *queryIDFactory) Next() uint64 {
  next := f.curr
  f.curr++
  return next
}
```

All child eval objects should refer to the same queryIDFactory instance.

The fix should be accompanied with a test case in topdown that at least verifies query IDs are unique. In addition, a test case covering partial eval with negation would be good.

The following policy can be used to reproduce the issue:

```
package x

p { 1 }
p { 2 }
```

Query to `data.x.p` should result in two child queries (one for each rule), each one should have a unique ID.

### PR DESCRIPTION
**Pull request by srenatus**
This is for issue #707.

I didn't go all the way to adding the partial test including `not` -- but this should cover the other bits.

Fixes #707

### CODE REVIEW

File: topdown/topdown_test.go [hunk 1]
```diff
@@ -57,6 +57,44 @@ func TestTopDownCompleteDoc(t *testing.T) {
...
+	queryIDs := map[uint64]bool{} // set of seen queryIDs (in EnterOps)
+	for _, evt := range tr {
+		if evt.Op != EnterOp {
+			continue
+		}
+		if queryIDs[evt.QueryID] {
+			t.Errorf("duplicate queryID: %v", evt)
+		}
+		queryIDs[evt.QueryID] = true
+	}
```
Comment (srenatus) [inline topdown/topdown_test.go]: There might be a more direct way of testing this -- but this is the only one I've found from a quick look around 😄

Comment (tsandall) [reply topdown/topdown_test.go]: This looks fine to me!

**Comment by srenatus** [comment]
@tsandall ✔️ squashed
