### PR TITLE
opa build -t wasm|plan: fail on unmatched entrypoints

### LINKED ISSUE #3957: opa build: deny entrypoints that don't map to module tree
Given a policy.rego like
```rego
package foo
default allow = false
allow { input.open == "sesame" }
```

It's unlikely that when a user calls `opa build -t wasm -e fox/allow policy.rego`, they want to have their entrypoints point to raw data, i.e. `data.fox.allow`. (It's more likely that they've made a typo.)

`opa build` should fail if the provided endpoints don't reference the module tree, but "just data".

There should be a new option that allows to go back to the old behaviour. Or perhaps we make it `--entrypoint` (`-e`) and `--data-entrypoint` for plain data refs. Since this will be a breaking change for users that use data refs, anyways, with the "revert to old behaviour" flag, too, we might as well just have them be explicit about their entry point types.

-------
This came up in #3953, where the mis-pointed entrypoint used quotes.

### PR DESCRIPTION
**Pull request by anderseknert**
Fixes #3957

Signed-off-by: Anders Eknert <anders@eknert.com>

### CODE REVIEW

File: compile/compile.go [hunk 1]
```diff
@@ -474,6 +475,8 @@ func (c *Compiler) compilePlan(ctx context.Context) error {
 			return err
 		}
 
+		queryPaths.Add(ast.StringTerm(c.entrypoints[i]))
```
Comment (tsandall) [inline compile/compile.go:478]: Instead of building this set here, call `c.compiler.GetRulesExeact(c.entrypointrefs[i])` here and check if the result is non-empty to test whether there is a ruleset defined at the entrypoint path.

One thing to consider is whether want the flag semantics to mean the entrypoint refers directly to the decision produced by a rule; or if we want to relax it a bit so they could refer to a package. If we want the latter, we could use GetRules instead.

File: compile/compile.go [hunk 2]
```diff
@@ -483,8 +486,28 @@ func (c *Compiler) compilePlan(ctx context.Context) error {
...
+		allPaths.Add(ast.StringTerm(modulePath))
+
+		for _, rule := range module.Rules {
+			rulePath, err := rule.Path().Ptr()
+			if err != nil {
+				return err
+			}
+			allPaths.Add(ast.StringTerm(rulePath))
+		}
+	}
```
Comment (tsandall) [inline compile/compile.go:506]: These changes can be removed if we rely on the rule tree by calling GetRulesExact (or GetRules) above.

File: compile/compile.go [hunk 3]
```diff
@@ -483,8 +486,28 @@ func (c *Compiler) compilePlan(ctx context.Context) error {
...
+
+	unmatchedQueryPaths := queryPaths.Diff(allPaths)
+	if unmatchedQueryPaths.Len() > 0 {
+		return fmt.Errorf("entrypoint(s) %v unmatched by any existing path in modules", unmatchedQueryPaths.String())
```
Comment (tsandall) [inline compile/compile.go:510]: nit: `entrypoint %v does not refer to a rule|decision|policy decision`

Not sure what term we should use but I think we should avoid saying "any existing path in modules". "rule" is probably the most understood.

File: compile/compile.go (hunk 1 above)
Comment (anderseknert) [reply compile/compile.go:478]: Neat, thanks! We use package names as entrypoints when we [compile](https://github.com/johanfylling/opa-compliance-test) the "YAML test suite" to plans for Jarl (or other IR implementations) to use for compliance tests. Would be good if we could keep it working that way :)

File: compile/compile.go (hunk 3 above)
Comment (anderseknert) [reply compile/compile.go]: Updated to something similar. It'll be singular now, and will just report on the first failure... but OTOH, chances should be pretty slim that someone provides a bunch of unmapped entrypoints.. and if they do, they would likely learn from the first error reported.. or what do you think?

File: compile/compile_test.go [hunk 4]
```diff
@@ -781,6 +786,41 @@ func TestCompilerPlanTargetPruneUnused(t *testing.T) {
...
+	files := map[string]string{
+		"test.rego": `package test
+
+		p := 7
+		q := p + 1`,
+	}
+
+	test.WithTempFS(files, func(root string) {
+
+		compiler := New().WithPaths(root).WithTarget("plan").WithEntrypoints("test/p", "test/q", "test/no")
```
Comment (srenatus) [inline compile/compile_test.go:799]: Do we already have "happy path" test cases? In this example, `test` is an entrypoint that should work, I suppose.

File: compile/compile.go [hunk 5]
```diff
@@ -464,6 +464,7 @@ func (c *Compiler) compilePlan(ctx context.Context) error {
 	// Create query sets for each of the entrypoints.
 	resultSym := ast.NewTerm(resultVar)
 	queries := make([]planner.QuerySet, len(c.entrypointrefs))
+	unmappedEntrypoints := ast.NewSet()
```
Comment (srenatus) [inline compile/compile.go:467]: [nit] If we're only storing strings, `map[string]struct{}{}` would do, too. But this is OK.

**Review by srenatus — DISMISSED** [review]
One question, one nitpick, This looks good, thanks!

File: compile/compile_test.go (hunk 4 above)
Comment (anderseknert) [reply compile/compile_test.go:799]: It should, but I can add one where only the happy path is hit 👍

File: compile/compile.go (hunk 5 above)
Comment (anderseknert) [reply compile/compile.go:467]: I'll try that 👍

Comment (anderseknert) [reply compile/compile.go]: Settled on `[]string` here so that the order is guaranteed.

File: compile/compile_test.go (hunk 4 above)
Comment (anderseknert) [reply compile/compile_test.go:799]: There were plenty of happy path tests for this already, so left it out.

File: ast/builtins.go [hunk 6]
```diff
@@ -1021,7 +1021,7 @@ var Concat = &Builtin{
 
 var FormatInt = &Builtin{
 	Name:        "format_int",
-	Description: "Returns the string representation of the number in the given base after converting it to an integer value.",
+	Description: "Returns the string representation of the number in the given base after rounding it down to an integer value.",
```
Comment (anderseknert) [inline ast/builtins.go:1024]: @srenatus I smuggled this change in here, since this surprised me yesterday. Not worth a PR of its own.

Comment (srenatus) [reply ast/builtins.go:1024]: Yeah but maybe an extra commit? We can rebase and merge this PR.

File: compile/compile.go [hunk 7]
```diff
@@ -418,7 +418,7 @@ func (c *Compiler) optimize(ctx context.Context) error {
 	return nil
 }
 
-func (c *Compiler) compilePlan(ctx context.Context) error {
+func (c *Compiler) compilePlan(_ context.Context) error {
```
Comment (srenatus) [inline compile/compile.go:421]: [nit]
```suggestion
func (c *Compiler) compilePlan(context.Context) error {
```

Comment (anderseknert) [reply compile/compile.go:421]: Sure... but can't we have linter rules for things like this? 😅

Comment (anderseknert) [reply compile/compile.go]: Done :)

File: ast/builtins.go (hunk 6 above)
Comment (anderseknert) [reply ast/builtins.go:1024]: I made the change in a separate commit now. Let me know if it looks alright.

**Review by srenatus — DISMISSED** [review]
Thank you!

**Review by srenatus — APPROVED** [review]
