### PR TITLE
Fix wrong type error message in count, object.filter, object.remove

### LINKED ISSUE #4767: Wrong message in runtime type check for count, object.filter and object remove
```
❯ echo '{"x":true}' | opa eval -I -f pretty --strict-builtin-errors 'object.remove({"a": 1}, input.x)'
```
> eval_type_error: object.remove: operand 2 must be one of {object, **string**, array} but got boolean

These functions do not accept string — that should be a **set** instead. Funny how we have 8 tests that assert this exact message, and nobody noticed!

The best test case was this one: 
```
expected topdown error text "object.remove: operand 2 must be one of {object, string, array} but got string"
```
😄

EDIT: Also found this in `count`, so fixing there as well.

### PR DESCRIPTION
**Pull request by anderseknert**
Fixes #4767

Signed-off-by: Anders Eknert <anders@eknert.com>

### CODE REVIEW

**Review by srenatus — DISMISSED** [review]

File: topdown/object.go [hunk 1]
```diff
@@ -148,7 +148,7 @@ func getObjectKeysParam(arrayOrSet ast.Value) (ast.Set, error) {
 			return nil
 		})
 	default:
-		return nil, builtins.NewOperandTypeErr(2, arrayOrSet, ast.TypeName(types.Object{}), ast.TypeName(types.S), ast.TypeName(types.Array{}))
+		return nil, builtins.NewOperandTypeErr(2, arrayOrSet, ast.TypeName(types.Object{}), ast.TypeName(types.Set{}), ast.TypeName(types.Array{}))
```
Comment (srenatus) [inline topdown/object.go:151]: Looks like in all other places, we've spelled them out: https://github.com/open-policy-agent/opa/search?q=NewOperandTypeErr

Comment (anderseknert) [reply topdown/object.go:151]: Yeah, that looks easier on the eyes.. I'll do the same here.

**Review by srenatus — APPROVED** [review]
