### PR TITLE
format: don't linebreak when there are generated vars in func call

### LINKED ISSUE #4018: OPA fails to load bundle when optimizations are enabled
OPA fails to load bundle when optimizations are enabled.

## Expected Behavior
First running `opa build -O=1 . -e rules/main/allowed` and then `opa run -s -b bundle.tar.gz` should successfully start the server.

## Actual Behavior
The exceptions shown in the image below are thrown:
image

Here is the corresponding un-optimized rego code:

```
bearer_token(auth_header) = t {
	startswith(auth_header, "Bearer ")
	parts := split(auth_header, " ")
	count(parts) == 2
	t := parts[1]
}
```

And the optimized rego code:

```
bearer_token(__local15__6) = __local17__6 {
	startswith(
		__local15__6,
		"Bearer ",
	)
	split(
		__local15__6, __local57__6,
		" ",
	)
	__local16__6 = __local57__6
	count(__local16__6, __local58__6)
	__local58__6 = 2
	__local17__6 = __local16__6[1]
}
```

Creating the same bundle without optimizations by using `opa build . -e rules/main/allowed` allows the server to be started normally:

image

## Steps to Reproduce the Problem

* OPA version: 
```
Version: 0.34.2
Build Commit: 9f11f21
Build Timestamp: 2021-11-10T18:33:08Z
Build Hostname: Mac-1636569091949.local
Go Version: go1.17.3
WebAssembly: available
```

### PR DESCRIPTION
**Pull request by srenatus**
Fixes #4018.

### CODE REVIEW

**Review by anderseknert — APPROVED** [review]

File: format/format.go [hunk 1]
```diff
@@ -853,10 +853,26 @@ func (w *writer) listWriter() entryWriter {
 // groupIterable will group the `elements` slice into slices according to their
 // location: anything on the same line will be put into a slice.
 func groupIterable(elements []interface{}, last *ast.Location) [][]interface{} {
+	generated := false
+	for _, e := range elements {
+		if t, ok := e.(*ast.Term); ok {
+			if v, ok := t.Value.(ast.Var); ok {
```
Comment (tsandall) [inline format/format.go:859]: Should we use a visitor here? I'm not sure if we can end up with cases like `f([__local0__])`

**Review by tsandall — DISMISSED** [review]
