### PR TITLE
fix: coverage limit overflow

### LINKED ISSUE #5284: Test coverage threshold can exceed 100%
## Short description 
When executing for example `opa test . -c --threshold 101` you get the error saying 
`Code coverage threshold not met: got 100.00 instead of 101.00`

A negative value is also accepted and used as any other number.

To avoid setting an unintended or impossible threshold, let's exit if the threshold is above 100 or less than 0

* Tested with OPA version 0.44.0

## Steps To Reproduce
Run tests with a code coverage threshold <0 or >100

## Expected behavior
If the threshold argument is <0 or >100, print this message and exit with a non-zero value
`Code coverage threshold must be between 0 and 100`

### PR DESCRIPTION
**Pull request by hzliangbin**
add a range check to threshold, fix #5284
Signed-off-by: Bin Liang <hzliangbin@foxmail.com>

### CODE REVIEW

File: cmd/test.go [hunk 1]
```diff
@@ -208,6 +208,11 @@ func opaTest(args []string) int {
 		return 1
 	}
 
+	if testParams.threshold < 0 || testParams.threshold > 100 {
```
Comment (srenatus) [inline cmd/test.go:211]: [nit] I think we could move this check higher up. Since we're going to end execution anyways if it fails, we can avoid the work done before.

**Review by srenatus — COMMENTED** [review]
Thanks for contributing! Would you mind adding a test case or two? Just so this doesn't get lost in future refactorings etc.

File: cmd/test.go (hunk 1 above)
Comment (anderseknert) [reply cmd/test.go:211]: @hzliangbin can you PTAL? :)

**Comment by hzliangbin** [comment]
@srenatus @anderseknert PTAL

**Review by srenatus — APPROVED** [review]
Thanks for contributing 🎈
