### PR TITLE
Override Cache-Control: no-store on force_cache

### LINKED ISSUE #2841: http.send: force_cache option does not override Cache-Control: no-store from server
## Expected Behavior

`force_cache`/`force_cache_duration_seconds` is documented as fields that "can be used to override the cache directives defined by the server". 

## Actual Behavior

The presence of a `Cache-Control: no-store` directive is still respected, and the response will not be cached. 

## Steps to Reproduce the Problem

OPA version 0.24.0+

Create an endpoint with a cache-control header including no-store in the response. Call it from `http.send` with `force_cache`/`force_cache_duration_seconds` set for forced caching. The endpoint will be called for each invocation of the policy.

### PR DESCRIPTION
**Pull request by anderseknert**
Fixes #2841

CC @ashutosh-narkar 

Signed-off-by: Anders Eknert <anders.eknert@bisnode.com>

### CODE REVIEW

File: topdown/http.go [hunk 1]
```diff
@@ -613,16 +613,18 @@ func checkHTTPSendInterQueryCache(bctx BuiltinContext, key ast.Object, req *http
 		}
 	}
 
-	err = insertIntoHTTPSendInterQueryCache(bctx, key, newValue, result, size)
+	force := cacheParams != nil && cacheParams.forceCacheDurationSeconds > 0
```
Comment (ashutosh-narkar) [inline topdown/http.go:616]: Since we are trying to override the `no-store` directive here, couldn't we just use the value of `force_cache` param to determine this. For ex, if `force_cache` is `true` override no-store, if not then decide logic based on the `no-store` directive from server.

Comment (anderseknert) [reply topdown/http.go:616]: Indeed - is this not what this is doing? 😅 In the following function call we check:

`(!force && !canStore(resp.Header))`

..so the `no-store` directive in the response will be checked unless `force_cache` is `true`.

Comment (ashutosh-narkar) [reply topdown/http.go:616]: I'm thinking what if we used `cacheParams != nil` itself as the override for `no-store`. We will have other cache parameters in the future apart from `forceCacheDurationSeconds`, so `cacheParams != nil` which implies `force_cache` is `true`. wdyt ?

Comment (anderseknert) [reply topdown/http.go:616]: Oh right, so like now but skipping the extra `cacheParams.forceCacheDurationSeconds > 0` check? Yeah that I added mostly due to not knowing what the intent of `force_cache = true` together with `force_cache_duration = 0` would be. I'll use only `cacheParams != nil` then.

Comment (anderseknert) [reply topdown/http.go]: Fixed 👍

**Review by ashutosh-narkar — APPROVED** [review]
lgtm

**Review by patrick-east — APPROVED** [review]
