### PR TITLE
planner: forget variables from comprehensions

### LINKED ISSUE #3325: wasm: "seen" local variable check has false positives (missing p.vars.Pop?)
On the surface, the issue looks like this:

```
$ opa eval -t rego  --format=pretty 'xs := numbers.range(1, 10); ys := { x | xs[x]}; zs := { x | xs[x] }'
+------------------------+-----------------------+-----------------------+
|           xs           |          ys           |          zs           |
+------------------------+-----------------------+-----------------------+
| [1,2,3,4,5,6,7,8,9,10] | [0,1,2,3,4,5,6,7,8,9] | [0,1,2,3,4,5,6,7,8,9] |
+------------------------+-----------------------+-----------------------+
$ opa eval -t wasm --format=pretty 'xs := numbers.range(1, 10); ys := { x | xs[x]}; zs := { x | xs[x] }'
+------------------------+-----------------------+-----+
|           xs           |          ys           | zs  |
+------------------------+-----------------------+-----+
| [1,2,3,4,5,6,7,8,9,10] | [7,0,2,4,8,5,1,3,6,9] | [9] |
+------------------------+-----------------------+-----+
```

Adding this case to `planner_test.go`, 

```
		{
			note:    "focus",
			queries: []string{`numbers.range(1, 10, xs); ys := { x | xs[x]}; zs := { x | xs[x] }`},
		},
```

we find this IR:

```
*ir.Policy Policy
| *ir.Static Static (5 strings, 1 files)
| | *ir.StringConst &{Value:xs}
| | *ir.StringConst &{Value:ys}
| | *ir.StringConst &{Value:zs}
| | *ir.StringConst &{Value:1}
| | *ir.StringConst &{Value:10}
| | *ir.BuiltinFunc &{Name:assign}
| | *ir.BuiltinFunc &{Name:numbers.range}
| | *ir.StringConst &{Value:<query>}
| *ir.Plans &{Plans:[Plan test (1 blocks)]}
| | *ir.Plan Plan test (1 blocks)
| | | *ir.Block Block (17 statements)
| | | | *ir.MakeNumberRefStmt &{Index:3 Target:Local<2> Location:{Index:0 Col:1 Row:1 file:<query> text:numbers.range(1, 10, xs)}}
| | | | *ir.MakeNumberRefStmt &{Index:4 Target:Local<3> Location:{Index:0 Col:1 Row:1 file:<query> text:numbers.range(1, 10, xs)}}
| | | | *ir.CallStmt &{Func:numbers.range Args:[Local<2> Local<3>] Result:Local<4> Location:{Index:0 Col:1 Row:1 file:<query> text:numbers.range(1, 10, xs)}}
| | | | *ir.AssignVarStmt &{Source:Local<4> Target:Local<5> Location:{Index:0 Col:1 Row:1 file:<query> text:numbers.range(1, 10, xs)}}
| | | | *ir.MakeSetStmt &{Target:Local<7> Location:{Index:0 Col:33 Row:1 file:<query> text:{ x | xs[x]}}}
| | | | *ir.BlockStmt BlockStmt (1 blocks) &{0 33 1 <query> { x | xs[x]}}
| | | | | *ir.Block Block (1 statements)
| | | | | | *ir.ScanStmt &{Source:Local<5> Key:Local<8> Value:Local<9> Block:Block (3 statements) Location:{Index:0 Col:39 Row:1 file:<query> text:xs[x]}}
| | | | | | | *ir.Block Block (3 statements)
| | | | | | | | *ir.AssignVarStmt &{Source:Local<8> Target:Local<10> Location:{Index:0 Col:39 Row:1 file:<query> text:xs[x]}}
| | | | | | | | *ir.NotEqualStmt &{A:Local<9> B:Bool<false> Location:{Index:0 Col:39 Row:1 file:<query> text:xs[x]}}
| | | | | | | | *ir.SetAddStmt &{Value:Local<10> Set:Local<7> Location:{Index:0 Col:33 Row:1 file:<query> text:{ x | xs[x]}}}
| | | | *ir.CallStmt &{Func:assign Args:[Local<6> Local<7>] Result:Local<11> Location:{Index:0 Col:33 Row:1 file:<query> text:{ x | xs[x]}}}
| | | | *ir.NotEqualStmt &{A:Local<11> B:Bool<false> Location:{Index:0 Col:33 Row:1 file:<query> text:{ x | xs[x]}}}
| | | | *ir.MakeSetStmt &{Target:Local<13> Location:{Index:0 Col:53 Row:1 file:<query> text:{ x | xs[x] }}}
| | | | *ir.BlockStmt BlockStmt (1 blocks) &{0 53 1 <query> { x | xs[x] }}
| | | | | *ir.Block Block (3 statements)
| | | | | | *ir.DotStmt &{Source:Local<5> Key:Local<10> Target:Local<14> Location:{Index:0 Col:59 Row:1 file:<query> text:xs[x]}}
| | | | | | *ir.NotEqualStmt &{A:Local<14> B:Bool<false> Location:{Index:0 Col:59 Row:1 file:<query> text:xs[x]}}
| | | | | | *ir.SetAddStmt &{Value:Local<10> Set:Local<13> Location:{Index:0 Col:53 Row:1 file:<query> text:{ x | xs[x] }}}
| | | | *ir.CallStmt &{Func:assign Args:[Local<12> Local<13>] Result:Local<15> Location:{Index:0 Col:53 Row:1 file:<query> text:{ x | xs[x] }}}
| | | | *ir.NotEqualStmt &{A:Local<15> B:Bool<false> Location:{Index:0 Col:53 Row:1 file:<query> text:{ x | xs[x] }}}
| | | | *ir.MakeObjectStmt &{Target:Local<16> Location:{Index:0 Col:1 Row:1 file:<query> text:numbers.range(1, 10, xs)}}
| | | | *ir.ObjectInsertStmt &{Key:String<0> Value:Local<5> Object:Local<16> Location:{Index:0 Col:1 Row:1 file:<query> text:numbers.range(1, 10, xs)}}
| | | | *ir.ObjectInsertStmt &{Key:String<1> Value:Local<6> Object:Local<16> Location:{Index:0 Col:1 Row:1 file:<query> text:numbers.range(1, 10, xs)}}
| | | | *ir.ObjectInsertStmt &{Key:String<2> Value:Local<12> Object:Local<16> Location:{Index:0 Col:1 Row:1 file:<query> text:numbers.range(1, 10, xs)}}
| | | | *ir.ResultSetAdd &{Value:Local<16> Location:{Index:0 Col:1 Row:1 file:<query> text:numbers.range(1, 10, xs)}}
```

and we note that the second check misses a scan. Sooo I'm fairly sure this is introduced by https://github.com/open-policy-agent/opa/pull/3287: when the second comprehension is planned, the `x` has been "seen", and the planner will not issue a scan. That is wrong ⚡

### PR DESCRIPTION
**Pull request by srenatus**
Before, variables introduced in a comprehension, like the `x` in

    { x | xs[x] }

would have been recorded in `p.vars`, and have an effect outside of
the scope of this comprehension, leading to wrong plans.

Now, we'll duplicate whatever variables we've known before, and
reset to that state after planning the comprehensions.

Fixes #3325.

### CODE REVIEW

File: internal/planner/planner.go [hunk 1]
```diff
@@ -1360,6 +1360,10 @@ func (p *Planner) planObjectComprehension(oc *ast.ObjectComprehension, iter plan
 
 func (p *Planner) planComprehension(body ast.Body, closureIter planiter, target ir.Local, iter planiter) error {
 
+	// Variables that have been introduced in this comprehension have
+	// no effect on other parts of the policy, so they'll be dropped
+	// below.
+	p.vars.Dup()
```
Comment (tsandall) [inline internal/planner/planner.go:1366]: We should be able to call `p.vars.Push(map[ast.Var]ir.Local{})` here instead of this new function. The `Get()` function will check the top of the stack, if not found continue to the next element, and so on. Maybe I'm missing something about why this new function is needed.

**Review by tsandall — APPROVED** [review]
LGTM assuming the `Dup()` call can be replaced w/ `Push()`.

File: internal/planner/planner.go (hunk 1 above)
Comment (srenatus) [reply internal/planner/planner.go:1366]: 🤦 Yep. Of course. I wasn't seeing the forest for the trees. Replacing.
