### PR TITLE
ast,format,planner: Add `not` block syntax

### LINKED ISSUE #8402: Update parser to accept `not {}` body syntax
This will guarantee that all valid ASTs can generate valid Rego, in cases where [unrolling](https://github.com/open-policy-agent/opa/issues/8394) compiler-generated expressions fails.

Also, someone might find it useful ;)

### PR DESCRIPTION
**Pull request by johanfylling**
Expanding the Rego syntax to support not-bodies (not blocks?): `not {...}`

For a not block to successfully evaluate, its body _must not_ successfully evaluate. If evaluation causes iteration, all evaluation paths must fail.

```rego
package example

import future.keywords.not

a if f([1, 2, 3])

b if f([1, 0, 3])

c if not {
    true
    false
}

f(lst) if not {
    some x in lst
    x == 0
}
```

```bash
$ opa eval -d policy.rego -fpretty 'data'
{
  "example": {
    "a": true,
    "c": true
  }
}
```

Fixes: #8402

### CODE REVIEW

File: internal/planner/planner.go [hunk 1]
```diff
@@ -637,12 +637,12 @@ func (p *Planner) planQuery(q ast.Body, index int, iter planiter) error {
...
 	switch {
-	case e.IsNegated():
-		return p.planNot(e, iter)
-
 	case len(e.With) > 0:
 		return p.planWith(e, iter)
 
+	case e.IsNegated():
+		return p.planNot(e, iter)
+
```
Comment (srenatus) [inline internal/planner/planner.go:645]: Hm? What is this about? 🤔

File: v1/ast/compile.go [hunk 2]
```diff
@@ -4661,6 +4661,10 @@ func unsafeNotVars(arity func(Ref) int, vis *VarVisitor, v any) bool {
 		return false
 	}
 
+	if n.ExplicitBody {
+		return true
+	}
```
Comment (srenatus) [inline v1/ast/compile.go:4666]: Reading this top-to-bottom, but right now, I don't get it. ExplicitBody means we'll short-circuit this check and say it _does contain unsafe vars_? Maybe reading the rest will clear the fog...

File: v1/ast/parser.go [hunk 3]
```diff
@@ -1318,7 +1322,11 @@ func (p *Parser) parseLiteralExpr(negated bool) *Expr {
 		}
 
 		if negated && p.notBodies {
+			// Move 'with' statement to outer not expr
+			w := expr.With
+			expr.With = nil
 			expr = NewExpr(&Not{Body: NewBody(expr), Location: p.s.Loc()})
+			expr.With = w
```
Comment (srenatus) [inline v1/ast/parser.go:1329]: Neat

File: v1/ast/parser_test.go [hunk 4]
```diff
@@ -9045,9 +9045,10 @@ func TestNotImport(t *testing.T) {
...
 		module string
 		exp    *Module
+		expErr string
 	}{
 		{
-			note: "no import",
+			note: "no import, implicit body (legacy negation)",
 			module: `package test
 				p if {
 					not 1 + 1 == 3
```
Comment (srenatus) [inline v1/ast/parser_test.go:9054]: 💭 `not 1 + 1` => `(not 1) + 1` => `0 + 1` => `1` ✔️ 😉

File: v1/format/testfiles/v0_to_v1/test_not_future_import.rego.formatted [hunk 5]
```diff
@@ -0,0 +1,8 @@
+package test
+
+import future.keywords.not
+import rego.v1
+
+a if {
+	not input.x + input.y == 2
+}
```
Comment (srenatus) [inline v1/format/testfiles/v0_to_v1/test_not_future_import.rego.formatted:8]: FTFY https://github.com/open-policy-agent/opa/pull/8564

**Review by srenatus — APPROVED** [review]
Solid! Thanks. I don't think I've found an answer to my line-4666 question above (below?), though

File: v1/ast/parser_test.go (hunk 4 above)
Comment (johanfylling) [reply v1/ast/parser_test.go:9054]: Or `((−∞,1)∪(1,∞)) + 1`, but that still holds up 😁.

File: internal/planner/planner.go (hunk 1 above)
Comment (johanfylling) [reply internal/planner/planner.go:645]: For not-bodies we'll drop the outer `with` modifier if we don't plan it out first. This didn't matter for legacy negation, as we'd just circle back and plan out the complement expression with the `with` still intact. This'll change the order in which these structures get planned out for the legacy case, but shouldn't affect the semantics.

File: v1/ast/compile.go (hunk 2 above)
Comment (johanfylling) [reply v1/ast/compile.go:4666]: Shout-circuiting here means that we'll treat the not-body as any other closure; e.g. `every`, comprehensions.

**Comment by johanfylling** [comment]
Got failing Wasm tests 😢. Investigating 🔍

File: v1/ast/compile.go (hunk 2 above)
Comment (srenatus) [reply v1/ast/compile.go:4666]: Ah! Thanks. 💡
