### PR TITLE
ast/compile: use all vars from rule body for index candidates

### LINKED ISSUE #3579: Comprehension indexing picks wrong candidates
The comprehension indexing feature is picking the wrong candidates for index keys (or is not restrictive enough) when there are nested comprehensions that close over variables in the outer-most body. For example:

```rego
p := {x: vs |
        some x
        q[x]

        vs := {y: vs2 |
                some y
                r[y]

                vs2 := {z |         # index created with 'y' as key
                        some z
                        s[z]
                        z[0] = x    # indexer excludes 'x' as a candidate
                        z[1] = y    # indexer includes 'y' as a candidate
                        # f(z, x, y)  # uncomment this line and comment previous two to see correct result
                }
        }
}

q["A"]
q["B"]
r["C"]
r["D"]
s[["A", "C"]]
s[["A", "D"]]
s[["B", "C"]]
```

In this case, the correct result for `p` is:

```json
{
        "A": {
            "C": [
                [
                    "A",
                    "C"
                ]
            ],
            "D": [
                [
                    "A",
                    "D"
                ]
            ]
        },
        "B": {
            "C": [
                [
                    "B",
                    "C"
                ]
            ],
            "D": []
        }
    }
```

However, because the compiler decides to index with only `y` as the index key, the actual result is:

```json
{
        "A": {
            "C": [
                [
                    "A",
                    "C"
                ],
                [
                    "B",
                    "C"
                ]
            ],
            "D": [
                [
                    "A",
                    "D"
                ]
            ]
        },
        "B": {
            "C": [
                [
                    "A",
                    "C"
                ],
                [
                    "B",
                    "C"
                ]
            ],
            "D": [
                [
                    "A",
                    "D"
                ]
            ]
        }
    }
```

This appears to be a bug in the comprehension index build [here](https://github.com/open-policy-agent/opa/blob/main/ast/compile.go#L1739). The indexer should either exclude the nested comprehension entirely (safer but worse performance) or it should include the correct candidates in the key.

### PR DESCRIPTION
**Pull request by srenatus**
Before, we'd only looked at the vars preceding the comprehension in the body
containing it. In the case of nested comprehensions, that would have excluded
the rule body OUTSIDE of the nested body.

Now, we'll accumulate candidates over multiple bodies -- capturing the ones
that had been missing before.

Fixes #3579.

-----------

I had a more involved fix first, but making it work with the query compiler, I realised that moving the `candiates.Copy()` does the trick, too.

The change to the existing tests also covers the issue underlying #3579, I believe.

### CODE REVIEW

File: ast/compile_test.go [hunk 1]
```diff
@@ -3674,6 +3679,11 @@ func TestCompilerBuildComprehensionIndexKeySet(t *testing.T) {
 					]
 				}
 			`,
+			// Note: no comprehension index for line 7 (`z = [ ...`)
+			expected: exp{9: {
```
Comment (srenatus) [inline ast/compile_test.go:3683]: This expectation is new: the nested comprehension is now indexed because `y`, previously hidden in the surrounding body of the `z` comprehension, is no now taken into account.

File: ast/compile.go [hunk 2]
```diff
@@ -1772,8 +1772,8 @@ func (ci *ComprehensionIndex) String() string {
 
 func buildComprehensionIndices(dbg debug.Debug, arity func(Ref) int, candidates VarSet, rwVars map[Var]Var, node interface{}, result map[*Term]*ComprehensionIndex) uint64 {
 	var n uint64
+	cpy := candidates.Copy()
```
Comment (tsandall) [inline ast/compile.go:1775]: I realized that nested bodies will see candidates from subsequent expressions because of how `WalkBodies` and the for-loop below interact... for example:

```rego
x = 7
y = {1 | ["foo" | ...]} # array comprehension nested inside set comprehension
z = 8
```

In this case, the candidate set will contain x and z when the nested array comprehension body is processed.

This shouldn't be a problem in practice because if the nested array comprehension does not close over `z` then it won't matter. If it does close over `z` then `z = 8` will be reordered before the outer set comprehension by an earlier stage.

File: ast/compile_test.go [hunk 3]
```diff
@@ -3661,7 +3666,7 @@ func TestCompilerBuildComprehensionIndexKeySet(t *testing.T) {
 			wantDebug: 1,
 		},
 		{
-			note: "skip: due to nested comprehension containing candidate",
+			note: "skip: due to nested comprehension containing candidate + indexed nested comprehension with key from rule body",
```
Comment (tsandall) [inline ast/compile_test.go:3669]: nit: "skip:" was intended for cases where no index gets built because it produce incorrect results, worsen performance, etc. Let's use a difference prefix ("mixed:"?) since an index is built now.

Comment (tsandall) [reply ast/compile_test.go:3669]: nit: I'd also update the comment in the module that says _'y' disqualifies indexing ..._ to be a bit less ambiguous... it disqualifies indexing of the outer comprehension.

File: ast/compile_test.go (hunk 1 above)
Comment (tsandall) [reply ast/compile_test.go:3683]: This looks correct to me. We can index the inner comprehension but not the outer one. There was an issue in the original indexing implementation that resulted in this test case/fix: https://github.com/open-policy-agent/opa/issues/2497

**Review by tsandall — DISMISSED** [review]

**Comment by srenatus** [comment]
Addressed the test comments, will rebase and merge.
