### PR TITLE
ast: Check for undefined functions before safety check

### LINKED ISSUE #1141: Undefined function reported as safety error in some cases
# Expected Behavior

If an undefined function is called, the error should clearly identify the problem.

# Actual Behavior

In some cases, the safety check fails first which results in an unsafe error which is confusing. 

# Steps to Reproduce the Problem

```
> p[x] { y := r(1); data.q[x] with input as y }
1 error occurred: 1:1: rego_unsafe_var_error: var x is unsafe

> p { y := r(1); y }
1 error occurred: 1:5: rego_unsafe_var_error: expression is unsafe
```

# Additional Info

Tested on v0.10.2

### PR DESCRIPTION
**Pull request by tsandall**
Previously, references to undefined functions were caught after the
safety check ran. As a result, if the function call contained one or
more unsafe variables, the compiler would report safety errors instead
of undefined function errors. This would hide the source of the
problem and result in confusion. For example, before:

> data.deadbeef(x)
1 error occurred: 1:1: rego_unsafe_var_error: var x is unsafe

After:

> data.deadbeef(x)
1 error occurred: 1:1: rego_type_error: undefined function data.deadbeef

Fixes #1141

### CODE REVIEW

File: ast/compile_test.go [hunk 1]
```diff
@@ -701,6 +699,52 @@ p2 := 2`})
...
+		undefined_global {
+			deadbeef(x)
+		}
+
+		undefined_dynamic_dispatch {
+			x = "f"; data.test2[x](1)  # not currently supported
+		}
+	`
+
+	module2 := `
```
Comment (patrick-east) [inline ast/compile_test.go]: nit: Is `module2` used for anything? Asking more out of curiosity to make sure I'm understanding the code 😄

File: ast/compile_test.go [hunk 2]
```diff
@@ -2888,6 +2932,11 @@ func TestQueryCompiler(t *testing.T) {
 			imports:  nil,
 			expected: fmt.Errorf("match error\n\tleft  : number\n\tright : null"),
 		},
+		{
+			note:     "undefined function",
+			q:        "data.deadbeef(x)",
+			expected: fmt.Errorf("rego_type_error: undefined function data.deadbeef"),
```
Comment (srenatus) [inline ast/compile_test.go]: [nit] There's no format string here, so this _could_ use `errors.New`. But this seems to be in line with the other cases. Also, I can't think of anymore more minor than this nitpick 😉

Comment (tsandall) [reply ast/compile_test.go]: This is just habit on my part. I'm going to leave as is for now since it's consistent with the rest but will keep errors.New in mind in future.
