### PR TITLE
re-do `with` conflicts: last one wins, in wasm and topdown

### LINKED ISSUE #2922: wasm: With keyword "target confict: internal error"
There are a handful of test cases which fail with an unexpected runtime error when evaluated with the Wasm SDK:

```
with target conflict: internal error
```

This includes the following test cases:

"withkeyword/with base doc exact value" --> [test/cases/testdata/withkeyword/test-withkeyword-1036.yaml](https://github.com/open-policy-agent/opa/blob/master/test/cases/testdata/withkeyword/test-withkeyword-1036.yaml)
"withkeyword/with base doc any index" --> [test/cases/testdata/withkeyword/test-withkeyword-1037.yaml](https://github.com/open-policy-agent/opa/blob/master/test/cases/testdata/withkeyword/test-withkeyword-1037.yaml)
"withkeyword/with virtual doc specific index" --> [test/cases/testdata/withkeyword/test-withkeyword-1037.yaml](https://github.com/open-policy-agent/opa/blob/master/test/cases/testdata/withkeyword/test-withkeyword-1037.yaml)
"withkeyword/undefined_1" --> [test/cases/testdata/withkeyword/test-withkeyword-1038.yaml](https://github.com/open-policy-agent/opa/blob/master/test/cases/testdata/withkeyword/test-withkeyword-1038.yaml)
"withkeyword/with virtual doc exact value" --> [test/cases/testdata/withkeyword/test-withkeyword-1040.yaml](https://github.com/open-policy-agent/opa/blob/master/test/cases/testdata/withkeyword/test-withkeyword-1040.yaml)
"withkeyword/with virtual doc any index" --> [test/cases/testdata/withkeyword/test-withkeyword-1041.yaml](https://github.com/open-policy-agent/opa/blob/master/test/cases/testdata/withkeyword/test-withkeyword-1041.yaml)
"withkeyword/with virtual doc not specific index" --> [test/cases/testdata/withkeyword/test-withkeyword-1043.yaml](https://github.com/open-policy-agent/opa/blob/master/test/cases/testdata/withkeyword/test-withkeyword-1043.yaml)

### PR DESCRIPTION
**Pull request by srenatus**
This was prompted by #2922. In the WASM implementation, with statements overlapping with existing data in an incompatible way (strings vs objects, for example) had returned a conflict error; in topdown, the with statement had won. However, in topdown, multiple incompatibly-overlapping with statements would yield a conflict error.

Discussing how to approach the issue in WASM, we've come to agree that **simpler semantics** for `with` statements that are "overlapping" (or "in conflict") wouldn't be too bad.

So, where before our topdown and WASM implementations declared defeat, like `input with input.foo as "x" with input.foo.bar as "y"`, it'll now resolve to the last applied statement: in this example, `{"foo": {"bar": "y"}}`.

As for backward compatibility, this change means that some policies that we're erroneous before would now be OK; so, not existing, working functionality is changed.

Fixes #2922.

### CODE REVIEW

File: internal/wasm/instruction/variable.go [hunk 1]
```diff
@@ -36,3 +36,19 @@ func (SetLocal) Op() opcode.Opcode {
 func (i SetLocal) ImmediateArgs() []interface{} {
 	return []interface{}{i.Index}
 }
+
+// TeeLocal represents the WASM tee_local instruction.
+type TeeLocal struct {
```
Comment (tsandall) [inline internal/wasm/instruction/variable.go:41]: 👍 I was meaning to go through and add this and replace any of the unnecessary `SetLocal => GetLocal` combinations.

File: topdown/eval.go [hunk 2]
```diff
@@ -2781,7 +2781,9 @@ func merge(a, b ast.Value) (ast.Value, bool) {
 	if ok1 && ok2 {
 		return mergeObjects(aObj, bObj)
 	}
-	return nil, false
+
+	// nothing to merge, a wins (the mock data)
```
Comment (tsandall) [inline topdown/eval.go:2785]: I noticed this could be called from `evalTree.extent()` as well (~L1761 is `merged, ok := merge(base, virtual)`) where we merge the result of computing the virtual document for some path with any base document data. Now the base document data will win (which is consistent with existing tests AFAIK.) 👍

Comment (tsandall) [reply topdown/eval.go:2785]: nit: I'd remove the parenthetical because this applies to merging of base and virtual docs as part of evalTree as well as values set by `with`.

File: topdown/input.go [hunk 3]
```diff
@@ -43,21 +43,23 @@ func mergeTermWithValues(exist *ast.Term, pairs [][2]*ast.Term) (*ast.Term, erro
...
 				done := false
 				for i := 1; i < len(target)-1 && !done; i++ {
-					if child := node.Get(target[i]); child == nil {
-						obj, ok := node.Value.(ast.Object)
-						if !ok {
-							return nil, errConflictingDoc
-						}
+					obj, ok := node.Value.(ast.Object)
+					if !ok {
+						return nil, errConflictingDoc // possible?
```
Comment (tsandall) [inline topdown/input.go:54]: I think the following statement would cause this:

```
> true with input as [] with input.foo as 1
1 error occurred: true with input as [] with input.foo as 1: eval_conflict_error: conflicting documents
```

Basically, if the root is a non-object value we'll error out here. I guess we need to special case that.

File: topdown/input.go [hunk 4]
```diff
@@ -43,21 +43,23 @@ func mergeTermWithValues(exist *ast.Term, pairs [][2]*ast.Term) (*ast.Term, erro
...
+					}
+					if child := obj.Get(target[i]); child == nil {
+						obj.Insert(target[i], ast.NewTerm(makeTree(target[i+1:], pair[1])))
+						done = true
+					} else if _, ok := child.Value.(ast.Object); !ok {
```
Comment (tsandall) [inline topdown/input.go:59]: nit: we could combine this into one branch by adding a helper function like `isObject(x *ast.Term) bool` that returns true if x.Value.(ast.Object) is true, otherwise false (including if x is nil).

**Review by tsandall — COMMENTED** [review]
See my comment in topdown/input.go. Other than that, LGTM.

File: topdown/input.go (hunk 3 above)
Comment (srenatus) [reply topdown/input.go]: Yep, indeed. Thank you!

File: topdown/input.go (hunk 4 above)
Comment (srenatus) [reply topdown/input.go]: Yeah, it hadn't bothered me as much when writing; looking at those lines this morning, combining them seems obvious 😄 Done.

File: internal/wasm/instruction/variable.go (hunk 1 above)
Comment (srenatus) [reply internal/wasm/instruction/variable.go:41]: Awked my way through, replaced the obvious ones (on subsequent lines).

**Comment by srenatus** [comment]
Thanks for the review. I should have addressed your comments, could you give it another glance, please? 😃

**Review by tsandall — APPROVED** [review]
LGTM
