### PR TITLE
Fix #2738 - undefined function for custom-builtins

### LINKED ISSUE #2738: rego_type_error undefined function for custom built-in function during bundle build
## Expected Behavior
After creating and registering a custom built-in function and compiling a custom opa binary, `opa build --bundle...` should build a bundle for policy referencing the custom built-in function.
## Actual Behavior
It fails with the following error:
```
error: 1 error occurred: /path/to/policy.rego:11: rego_type_error: undefined function <name_of_custom_func>
```
## Steps to Reproduce the Problem

* OPA version 0.23.2

@patrick-east reproduced this using the example custom built-in [in this comment](https://github.com/open-policy-agent/opa/issues/2723#issuecomment-700910428).

## Additional Info

This error does not occur when testing the same policy using `opa run`.

### PR DESCRIPTION
**Pull request by gshively11**
The build and check commands were retrieving registered builtins too
early during initial execution, which did not give enough time for
custom binaries to register custom builtin functions. This change
sets the initial capabilities flag to nil instead, and then retrieves built-ins
immediately prior to instantiating a new compiler. This prevents an
undefined function rego_type_error during the build and check commands.
Fixes #2738.

This is my commit message

Signed-off-by: Grant Shively <gshively@godaddy.com>

### CODE REVIEW

File: cmd/flags.go [hunk 1]
```diff
@@ -144,7 +144,9 @@ type capabilitiesFlag struct {
 
 func newcapabilitiesFlag() *capabilitiesFlag {
 	return &capabilitiesFlag{
-		C: ast.CapabilitiesForThisVersion(),
+		// cannot call ast.CapabilitiesForThisVersion here because
+		// custom builtins cannot be registered by this point in execution
+		C: nil,
```
Comment (patrick-east) [inline cmd/flags.go:149]: Nice catch! 👍

**Review by patrick-east — APPROVED** [review]
Thanks for the fix! Changes LGTM
