### PR TITLE
Fix false positives in bundle root check

### LINKED ISSUE #2868: server: PUT v1/data handler performing string prefix check on bundle roots
The PUT v1/data handler calls `checkPathScope` which in turn uses `strings.HasPrefix` to check for conflicts with bundle roots: https://github.com/open-policy-agent/opa/blob/master/server/server.go#L1943. This leads to false-positive errors. For example, if the bundle roots are `["foo"]` and the caller sends `PUT v1/data/fo` the request will be rejected because `fo` is a prefix of `foo`.

### PR DESCRIPTION
**Pull request by anderseknert**
Allow writing to /data/foo when /data/foobar is a bundle root.

Fixes #2868

Signed-off-by: Anders Eknert <anders@eknert.com>

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -1993,10 +1993,16 @@ func (s *Server) checkPathScope(ctx context.Context, txn storage.Transaction, pa
 	}
 
 	spath := strings.Trim(path.String(), "/")
```
Comment (srenatus) [inline server/server.go:1995]: 💭 Do we need to worry about `foo/../bar` etc, or do these either not work at all, or are they cleaned before reaching this?

File: server/server.go [hunk 2]
```diff
@@ -1993,10 +1993,16 @@ func (s *Server) checkPathScope(ctx context.Context, txn storage.Transaction, pa
...
+
+	if spath == "" && len(bundleRoots) > 0 {
+		return types.BadRequestErr("can't write to document root with bundle roots configured")
+	}
 
 	for name, roots := range bundleRoots {
 		for _, root := range roots {
-			if strings.HasPrefix(spath, root) || strings.HasPrefix(root, spath) {
+			rootBase := strings.Split(root, "/")[0]
+			if spathBase == rootBase {
```
Comment (srenatus) [inline server/server.go:2005]: I might just be confused (and that's rather likely), but would we not end up being too strict here?

```golang
	spathBase := strings.Split("foo/bar/baz", "/")[0]
	rootBase := strings.Split("foo/bar/quz", "/")[0]
	fmt.Println(spathBase, rootBase, spathBase == rootBase)
```
This prints `[foo foo true]`, but the paths don't actually overlap.

**Review by srenatus — COMMENTED** [review]
Thanks for picking this up! I've briefly dug into the code, but I wasn't able to quickly answer these questions myself, so here we go 🙃 👇

File: server/server.go (hunk 2 above)
Comment (anderseknert) [reply server/server.go:2005]: Yep, should have marked as WIP - working on taking each path component into account now.

File: server/server.go (hunk 1 above)
Comment (anderseknert) [reply server/server.go:1995]: I think that's handled by the router before this, but it's an excellent test case regardless - will add 👍

Comment (anderseknert) [reply server/server.go:1995]: Indeed, it's handled before this - so if we do PUT on `/data/a/../a/b` it will respond with a redirect to `/data/a/b` which would be blocked. Testing turned out to be a bit hairy here since we'd need to change the behavior of the test client "globally" to follow redirects so I'll drop that for now.

**Review by srenatus — APPROVED** [review]
LGTM

File: server/server.go [hunk 3]
```diff
@@ -1993,10 +1993,15 @@ func (s *Server) checkPathScope(ctx context.Context, txn storage.Transaction, pa
 	}
 
 	spath := strings.Trim(path.String(), "/")
+	spathParts := strings.Split(spath, "/")
+
+	if spath == "" && len(bundleRoots) > 0 {
```
Comment (ashutosh-narkar) [inline server/server.go:1998]: Nit: This check can be moved before the `Split`.

Comment (anderseknert) [reply server/server.go:1997]: Fixed.

**Review by srenatus — APPROVED** [review]
