### PR TITLE
server: URL decode policy IDs

### LINKED ISSUE #2116: v1/policies requests don't do URL decoding for policy id's
# Expected Behavior
I should be able to push a policy into OPA with an `id` like `a policy` and then have it stored under that string. I should also be able to request for policies with leading `/`'s 

For example:

```
curl -X PUT -H "Content-Type: text/plain" --data-binary @/tmp/policy.rego 'http://localhost:8181/v1/policies/a%20policy'
```

or

```
curl -X PUT -H "Content-Type: text/plain" --data-binary @/tmp/policy.rego 'http://localhost:8181/v1/policies/%2Fa/policy'
```
^ for `/a/policy` as the `id`

# Actual Behavior
The string isn't decoded from the URL so the result is:

```
{12:22} ~/p/g/s/g/o/opa:issue/2099 ✓ ❯ curl -s -X GET 'http://localhost:8181/v1/policies' | jq
{
  "result": [
    {
      "id": "a%20policy",
      "raw": "package foo\n\np {\n    true\n}\n",
      "ast": {
        "package": {
          "path": [
            {
              "type": "var",
              "value": "data"
            },
            {
              "type": "string",
              "value": "foo"
            }
          ]
        },
        "rules": [
          {
            "head": {
              "name": "p",
              "value": {
                "type": "boolean",
                "value": true
              }
            },
            "body": [
              {
                "index": 0,
                "terms": {
                  "type": "boolean",
                  "value": true
                }
              }
            ]
          }
        ]
      }
    },
    {
      "id": "%2Fa/policy",
      "raw": "package foo\n\np {\n    true\n}\n",
      "ast": {
        "package": {
          "path": [
            {
              "type": "var",
              "value": "data"
            },
            {
              "type": "string",
              "value": "foo"
            }
          ]
        },
        "rules": [
          {
            "head": {
              "name": "p",
              "value": {
                "type": "boolean",
                "value": true
              }
            },
            "body": [
              {
                "index": 0,
                "terms": {
                  "type": "boolean",
                  "value": true
                }
              }
            ]
          }
        ]
      }
    }
  ]
}
```

Which I guess is maybe OK, they're unique and you can indeed just copy them literally and make the DELETE/GET calls on them.. except if you happened to have an ID already in the store that had a space or leading slash... (maybe from a plugin? /me looks at the bundle plugin..). For example with an 'id' like: `/bundles/a/b/c.rego` it does not appear possible to make a request for that path. If you send it to `/v1/policies/bundles//a/b/c.rego` it redirects to `/v1/policies/bundles/a/b/c.rego` which is wrong (missing the leading `/` on the id), and `/v1/policies/bundles/%2Fa/b/c.rego` uses the encoded ID (also wrong).

# Additional Info
I'm not sure how much changing this will impact any existing users.

### PR DESCRIPTION
**Pull request by mattmahn**
Policy IDs will be decoded in GET, PUT, and DELETE requests to the /policies endpoint.  This will enable users to include non-alphanumeric characters in policy IDs, as well as leading forward slashes, by URL encoding the path component of their requests.

Fixes #2116

### CODE REVIEW

File: server/server_test.go [hunk 1]
```diff
@@ -2311,6 +2312,48 @@ func TestPoliciesPathSlashes(t *testing.T) {
...
+
+	if f.recorder.Code != 200 {
+		t.Fatalf("Expected success but got %v", f.recorder)
+	}
+
+	// end PUT policy with URL encoded ID
+	f.reset()
+	// GET policy with URL encoded ID
+
+	get := newReqV1(http.MethodGet, "/policies", "")
```
Comment (anderseknert) [inline server/server_test.go:2332]: Is the policy ID not missing here?

File: server/server_test.go [hunk 2]
```diff
@@ -2311,6 +2312,48 @@ func TestPoliciesPathSlashes(t *testing.T) {
...
+	f.server.Handler.ServeHTTP(f.recorder, get)
+	if f.recorder.Code != 200 {
+		t.Fatalf("Expected success but got %v", f.recorder)
+	}
+	var listResponse types.PolicyListResponseV1
+	if err := json.NewDecoder(f.recorder.Body).Decode(&listResponse); err != nil {
+		t.Fatalf("Unexpected unmarshal error: %v", err)
+	}
+
+	if listResponse.Result[0].ID != expectedPolicyID {
```
Comment (anderseknert) [inline server/server_test.go:2342]: OK, so I guess that was meant so since you're extracting the ID from a list response here, but I'm not 100% sure I follow why :)

**Review by anderseknert — COMMENTED** [review]
Some questions, but looks good!

File: server/server_test.go (hunk 2 above)
Comment (mattmahn) [reply server/server_test.go:2342]: There not a particular reason, that's just what I did 🤷‍♂️
I'll change it to fetch that specific policy later today

Comment (mattmahn) [reply server/server_test.go]: ok, "today" is a different day, but it is done

**Review by anderseknert — APPROVED** [review]
LGTM. Thanks!
