### PR TITLE
plugins/logs: Fixes unintended mutation of result

### LINKED ISSUE #2752: Mask data in decision log, but not /v1/data response.
## Expected Behavior

When input/result is masked, e.g. `mask["/result/something_sensitive"]`, it should be removed from the decision logs, but not from the `/v1/data` API response (optionally?).  Decision logs tend to be shipped centrally, and sensitive data should be removed from those, but the `/v1/data` API response should still contain that data so that calling apps can use it as needed.

## Actual Behavior

When `mask` is used, it impacts both the decision logs and the `/v1/data` API response.

## Steps to Reproduce the Problem

OPA version: 0.24.0-dev

### PR DESCRIPTION
**Pull request by gshively11**
When mask rules targeted /result, it was modifying both the result
in the decision logs (intended) and the result in the API
response (unintended). Added a step to deep copy the result only once, if
there is at least one mask rule targeting the result.

Fixes #2752
Signed-off-by: Grant Shively gshively@godaddy.com

### CODE REVIEW

File: plugins/logs/plugin.go [hunk 1]
```diff
@@ -780,3 +795,26 @@ func (p *Plugin) logEvent(event EventV1) error {
...
+		}
+		return interface{}(objCopy), nil
+	default:
+		return nil, fmt.Errorf("unexpected type when decoding during deep copy")
+	}
+}
+
+func init() {
+	gob.Register(map[string]interface{}{})
+}
```
Comment (tsandall) [inline plugins/logs/plugin.go:820]: There's a manual deep copy implementation in storage/inmem/txn.go that will work for this case where the result types are known: https://github.com/open-policy-agent/opa/blob/master/storage/inmem/txn.go#L391. Let's use that one instead. It handles the case where the result is a slice and should be quite a bit faster. If you don't mind, take the implementation from txn.go and move it into an internal package like `internal/deepcopy` and then make use of it here.

File: plugins/logs/plugin.go [hunk 2]
```diff
@@ -711,7 +713,20 @@ func (p *Plugin) maskEvent(ctx context.Context, txn storage.Transaction, event *
...
+		// to the consumer
+		if mRule.escapedParts[0] == "result" && !resultCopied {
+			resultCopy, err := deepCopy(*event.Result)
+			if err != nil {
+				p.logError("failed to deep copy result for masking, rule skipped: %s: %s", mRule.String(), err.Error())
+				continue
+			}
+			event.Result = &resultCopy
+			resultCopied = true
+		}
```
Comment (tsandall) [inline plugins/logs/plugin.go:729]: Nit: let's do the deep copy inside the mask implementation rather than outside: https://github.com/open-policy-agent/opa/blob/master/plugins/logs/mask.go#L145

File: plugins/logs/plugin_test.go [hunk 3]
```diff
@@ -802,13 +804,35 @@ func TestPluginMasking(t *testing.T) {
...
-			expected: map[string]interface{}{
+			expectedInput: map[string]interface{}{
 				"is_sensitive": true,
 				"jwt":          "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.KipSRURBQ1RFRCoq",
 				"bar":          1,
 				"foo":          []interface{}{map[string]interface{}{"changed": json.Number("1")}},
 			},
 		},
+		{
+			note: "complex result erase (deep copy)",
```
Comment (tsandall) [inline plugins/logs/plugin_test.go:815]: Let's do this testing on the mask implementation in mask_test.go; we already have similar test cases there so I think we just have to modify `TestMaskRuleMask` in mask_test.go to check that the original result is unmodified.

**Review by tsandall — COMMENTED** [review]
@gshively11 thanks for submitting this! Left a few comments on the implementation.

File: plugins/logs/plugin.go (hunk 2 above)
Comment (gshively11) [reply plugins/logs/plugin.go:729]: `mRule.Mask` is iterated on though, and we only want to deep copy Result once, right?  We have to keep the state tracking whether or not Result had been modified somewhere, which is why I did it outside the loop and in plugin.go. If we do it in `mRule.Mask` the only spot I can see to store that state would be on event itself, is that ok?  If that works, or if there's another option I'm not seeing, I'm happy to make the change.

Comment (tsandall) [reply plugins/logs/plugin.go:729]: > mRule.Mask is iterated on though, and we only want to deep copy Result once, right?

Ah, good catch. I haven't looked at the masking in a while.

> If that works, or if there's another option I'm not seeing, I'm happy to make the change.

I think what I would do is just modify `resultValueToMaskRules` to return a struct (e.g., `maskRuleSet`) rather than a raw slice. Then we could put the iteration into the struct implementation and do the deep copy there. That way the details of the masking are handled in one place as opposed to being split across the plugin and the mask.go file.

Comment (gshively11) [reply plugins/logs/plugin.go:729]: Gotcha, that sounds reasonable. I'll take a crack at that soon.  Thanks for the feedback!

**Comment by gshively11** [comment]
Let me know if that `OnError` pattern is idiomatic for golang...I wasn't sure how to handle the logging since previously the iteration was in plugin.go, which had access to the plugin logger, but doesn't in mask.go, and I didn't want to pass the whole plugin in...

File: internal/deepcopy/deepcopy.go [hunk 4]
```diff
@@ -0,0 +1,23 @@
+package deepcopy
+
+// DeepCopy performs a recursive deep copy for nested slices/maps and
+// returns the copied object. Supports []interface{}
+// and map[string]interface{} only
+func DeepCopy(val interface{}) interface{} {
```
Comment (tsandall) [inline internal/deepcopy/deepcopy.go:6]: nit: I'd add some test coverage here now that this is exposed for re-use within the rest of OPA.

**Review by tsandall — COMMENTED** [review]
Just one comment about adding some test coverage for the deep copy utility. Other than that, LGTM.

File: plugins/logs/mask.go [hunk 5]
```diff
@@ -254,20 +261,20 @@ func (r maskRule) mkdirp(node map[string]interface{}, path []string, value inter
 	return nil
 }
 
-func resultValueToMaskRules(rv interface{}) ([]*maskRule, error) {
-
+func newMaskRuleSet(rv interface{}, onRuleError func(*maskRule, error)) (*maskRuleSet, error) {
```
Comment (tsandall) [inline plugins/logs/mask.go:264]: `onRuleError` looks fine to me; definitely better than creating a cyclic dependency or adding logging into the mask.go file.

**Comment by gshively11** [comment]
I spent a while trying to make something that could recursively compare the reference of the deep copy target/result, but I just don't have enough golang experience to pull that off, so I just went with this more simplistic mutation test, hope that's ok.

**Review by tsandall — APPROVED** [review]
LGTM. @gshively11 can you squash your commits? Once that's done we can merge this.

**Review by tsandall — APPROVED** [review]
LGTM
