### PR TITLE
Fix issue in array.flatten handling of single item arrays

### LINKED ISSUE #8272: array.flatten not properly flattening single item array
This flattens as intended:
```rego
array.flatten([-1, 1, [2, 2]]) #  => [-1, 1, 2, 2] 
```

This doesn't: 
```rego
array.flatten([-1, 1, [2]]) # => [-1,1,[2]]
```

### PR DESCRIPTION
**Pull request by anderseknert**
Fixes #8272

### CODE REVIEW

File: v1/topdown/array.go [hunk 1]
```diff
@@ -51,14 +51,16 @@ func builtinArrayFlatten(_ BuiltinContext, operands []*ast.Term, iter func(*ast.
...
 
 	for i := range size {
 		if nested, ok := arr.Elem(i).Value.(*ast.Array); ok {
+			containsArray = true
 			preAlloc += nested.Len() - 1
 		}
 	}
 
-	if size == preAlloc {
+	if !containsArray && size == preAlloc {
```
Comment (srenatus) [inline v1/topdown/array.go:63]: ooooh it was the `size([1]) == 1` case 💡

**Review by srenatus — APPROVED** [review]

File: v1/topdown/array.go (hunk 1 above)
Comment (anderseknert) [reply v1/topdown/array.go:63]: Indeed! But wouldn't happen on `[[1, 2], [3]]`  as that'd be size == 3 and not 2. Which is how this passed by unnoticed.
