### PR TITLE
topdown/parse_units: Use big.Rat for units parsing.

### LINKED ISSUE #4856: units.parse has inconsistent rounding errors for values of 0.5
## Short description 
`units.parse` has rounding errors when calculating `0.5` during conversion with the _milli-_ suffix (lowercase `m`) and _Kilo-_ (`k`/`K`). All other prefixes seem to calculate properly.

### System Details:
* **OPA version**: >= v0.41.0 (checked against both 0.41.0 and 0.42.0)
* **OS**: RHEL 7.9, UEK 5.4.17 
* **Go Version**: go1.16.4 linux/amd64
* Built locally with the following command/flags
```
 go build -o opa -ldflags "\
		-X github.com/open-policy-agent/opa/internal/report.ExternalServiceURL='' \
		-X github.com/open-policy-agent/opa/version.Version=local-unofficial \
		-X github.com/open-policy-agent/opa/version.Vcs=`./build/get-build-commit.sh` \
		-X github.com/open-policy-agent/opa/version.Timestamp=`./build/get-build-timestamp.sh` \
		-X github.com/open-policy-agent/opa/version.Hostname=`./build/get-build-hostname.sh`"
```

## Steps To Reproduce
1. Execute `opa run`
2. Run `units.parse("500m")` 
3. Receive rounding error of `0.5000000000000000104`
4. Run `units.parse("0.0005K")`
5. Receive rounding error of `0.49999999999999999997`

```
> units.parse("0.0000000000000000005E")
0.5
> units.parse("0.0000000000000005P")
0.5
> units.parse("0.0000000000005T")
0.5
> units.parse("0.0000000005G")
0.5
> units.parse("0.0000005M")
0.5
> units.parse("0.0005K")
0.49999999999999999997
> units.parse("0.5")
0.5
> units.parse("500m")
0.5000000000000000104

# Testing equality
> units.parse("0.0000000000000000005E") == 0.5
true
> units.parse("0.0000000000000005P") == 0.5
true
> units.parse("0.0000000000005T") == 0.5
true
> units.parse("0.0000000005G") == 0.5
true
> units.parse("0.0000005M") == 0.5
true
> units.parse("0.0005K") == 0.5
false
> units.parse("0.5") == 0.5
true
> units.parse("500m") == 0.5
false
```
## Expected behavior
All units that should be parsed to the same value should equal the same value (all 0.5s should be equal)
```
> units.parse("500m")
0.5
> units.parse("0.0005K")
0.5
```

### PR DESCRIPTION
**Pull request by philipaconrad**
Previously, we used `big.Float` for units parsing, but this resulted in occasional rounding issues, due to values like `0.001` not being perfectly representable in floating-point format.

This issue was fixed by switching units parsing to use `big.Rat`, since Rationals can generally handle such quantities with perfect precision.

A few new regression test cases have been added to the test suite, lifted almost verbatim from the original issue.

Fixes #4856.

### CODE REVIEW

File: topdown/parse_units.go [hunk 1]
```diff
@@ -70,43 +69,52 @@ func builtinUnits(_ BuiltinContext, operands []*ast.Term, iter func(*ast.Term) e
...
 	}
 
-	numFloat.Mul(numFloat, &x)
+	numRat.Mul(numRat, &x)
+
+	// When using just big.Float, we had floating-point precision
+	// issues because quantities like 0.001 are not exactly representable.
+	// Rationals (such as big.Rat) do not suffer this problem, but are
+	// more expensive to compute with in general.
+	numFloat, ok := new(big.Float).SetString(numRat.FloatString(10))
```
Comment (srenatus) [inline topdown/parse_units.go:114]: Can we shortcut this? `FloatToNumber` is just `f.Text(...)`: https://github.com/open-policy-agent/opa/blob/main/topdown/builtins/builtins.go#L171 -- if `big.Rat` has a similar method, we can forego the big.Float conversion

Comment (philipaconrad) [reply topdown/parse_units.go]: Good suggestion! I rolled that in to the latest version.

**Review by srenatus — APPROVED** [review]
