### PR TITLE
plugins: inter-query cache config discovery

### LINKED ISSUE #2978: Possible memory leak involving topdown/http?
## Expected Behavior

Using the http built-in with cache enabled should completely free up memory after cache expiration.

## Actual Behavior

We've been running OPA in production the last few days and it seems like there might be a memory leak involving the HTTP built-in.

possible_leak

Screen Shot 2020-12-04 at 8 35 45 AM

I found a few spots where I think [an HTTPResponse isn't being closed properly](https://github.com/godaddy/opa/commit/42d618d3aa7b8e6b1a00176bcf72edcef4092628), but after running it overnight with those changes it still seems to be leaking.  I'm going to keep digging, but I know very little about how OPA evaluates and caches things, so I could use some help finding the root cause.

## Steps to Reproduce the Problem

* OPA version: 0.25.0-dev, [forked with a few tweaks](https://github.com/godaddy/opa/tree/main-fork), but nothing in the path of this leak as far as I can tell.

### PR DESCRIPTION
**Pull request by gshively11**
InterQueryBuiltinCacheConfig now responds to the plugin manager's reconfigure event, which allows cache config to exist in discovery config. Previously, cache config would be ignored if it was only declared in discovery config.

(I still need to do tests, getting feedback on implementation before writing them)

Related to #2978

Signed-off-by: Grant Shively <gshively@godaddy.com>

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -253,6 +254,7 @@ func (s *Server) WithMetrics(m Metrics) *Server {
 // WithManager sets the plugins manager used by the server.
 func (s *Server) WithManager(manager *plugins.Manager) *Server {
 	s.manager = manager
+	s.manager.RegisterReconfigureListener(s.updateConfig)
```
Comment (ashutosh-narkar) [inline server/server.go:257]: We can probably move this registration in the server's `Init` function.

File: server/server.go [hunk 2]
```diff
@@ -2209,6 +2211,10 @@ func (s *Server) generateDefaultDecisionPath() string {
 	return p
 }
 
+func (s *Server) updateConfig(config *cfg.Config, cacheConfig *iCache.Config) {
```
Comment (ashutosh-narkar) [inline server/server.go:2214]: Nit: We are not really using the OPA config here only the cache config. What do you think about changing this to something like `cacheConfigUpdated(cacheConfig *iCache.Config) `

File: topdown/cache/cache.go [hunk 3]
```diff
@@ -110,6 +111,15 @@ func (c *cache) Delete(k ast.Value) {
 	c.unsafeDelete(k)
 }
 
+func (c *cache) UpdateConfig(config *Config) {
+	if config == nil {
+		return
+	}
+	c.mtx.Lock()
+	defer c.mtx.Unlock()
+	c.limit = *config.InterQueryBuiltinCache.MaxSizeBytes
```
Comment (ashutosh-narkar) [inline topdown/cache/cache.go:120]: Nit: Currently our cache config only contains one configurable parameter ie `size`. What if we maintain the config on the `cache` implementation and add a helper maybe to fetch the limit ? This would also make the function name more apt imo.

File: plugins/plugins.go [hunk 4]
```diff
@@ -153,6 +153,7 @@ type Manager struct {
 	initialized                  bool
 	interQueryBuiltinCacheConfig *cache.Config
 	gracefulShutdownPeriod       int
+	reconfigureListeners         []func(*config.Config, *cache.Config)
```
Comment (ashutosh-narkar) [inline plugins/plugins.go:156]: What about something like `registeredCacheTriggers   []func(*cache.Config)` ?

**Review by ashutosh-narkar — COMMENTED** [review]
Thanks for making these changes @gshively11 ! The implementation looks good. Few small comments on the function definitions etc.

File: server/server.go (hunk 2 above)
Comment (gshively11) [reply server/server.go:2214]: I'm fine with that, added it for the sake of future-proofing it, but maybe it's just YAGNI.

File: topdown/cache/cache.go (hunk 3 above)
Comment (gshively11) [reply topdown/cache/cache.go:120]: I'm good with that

File: plugins/plugins.go (hunk 4 above)
Comment (gshively11) [reply plugins/plugins.go:156]: I'm good with that if we're going to eliminate `*config.Config`.

File: topdown/cache/cache.go [hunk 5]
```diff
@@ -142,3 +152,11 @@ func (c *cache) unsafeDelete(k ast.Value) {
 	c.usage -= int64(value.SizeInBytes())
 	delete(c.items, k.String())
 }
+
+// MaxSizeBytes returns the current maximum size of the inter query cache in bytes.
+func (c *cache) MaxSizeBytes() int64 {
```
Comment (ashutosh-narkar) [inline topdown/cache/cache.go:157]: Nit: We don't need to export this function.

File: topdown/cache/cache.go [hunk 6]
```diff
@@ -110,11 +111,20 @@ func (c *cache) Delete(k ast.Value) {
 	c.unsafeDelete(k)
 }
 
+func (c *cache) UpdateConfig(config *Config) {
+	if config == nil {
```
Comment (ashutosh-narkar) [inline topdown/cache/cache.go:115]: I wonder if we will hit this condition 🤔

**Review by ashutosh-narkar — COMMENTED** [review]
@gshively11 changes look good.

File: topdown/cache/cache.go (hunk 6 above)
Comment (gshively11) [reply topdown/cache/cache.go:115]: Not as it's currently coded, but I think it's prudent defensive code. It's hard to predict how folks wrapping OPA might use the cache.

**Review by srenatus — APPROVED** [review]
LGTM

**Comment by gshively11** [comment]
Hmm, after testing this over the last few days, it still seems like we have a leak even with this change.  Going to keep digging, but I'm putting this on hold until I can find a root cause.

**Comment by ashutosh-narkar** [comment]
@gshively11 I'll move this PR in draft mode while we try to investigate the root cause.

**Comment by gshively11** [comment]
Heads up, I added a couple of `Close` calls for http responses generated by the http built-in...I don't _think_ it made a difference in my memory tests, but it seems like they should be there regardless?

**Comment by ashutosh-narkar** [comment]
@gshively11 I think the issue is how we calculate the size of the response and how we use that value to eventually insert the item in the cache. When we generate the AST response from the HTTP response, the `formatHTTPResponseToAST` function returns the size of the raw HTTP response message body and not the AST response itself which ends up in the cache. So the insert operation of the cache uses a `SizeInBytes()` value that is not a true indication of the actual size of the item going into the cache and hence the underlying structures end up consuming much more memory. I wonder if we based the insert logic on the actual size of the AST response and not just the raw HTTP response, we could help resolve https://github.com/open-policy-agent/opa/issues/2978. WDYT ?

**Comment by gshively11** [comment]
That thought had crossed my mind @ashutosh-narkar, but I wasn't sure if it was a good idea in this PR, given the issues with backwards compatibility and all.  But I do agree it would make the cache behavior much clearer. Would it be acceptable to use this PR as-is, then file a separate improvement issue/PR to handle the breaking behavior?

File: docs/content/configuration.md [hunk 7]
```diff
@@ -548,7 +548,7 @@ The following signing algorithms are supported:
 
 ### Caching
 
-Caching represents the configuration of the inter-query cache that built-in functions can utilize.
+Caching represents the configuration of the inter-query cache that built-in functions can utilize. Be aware that the total memory used by the cached items is significantly more than the bytes tracked for the max limit, around 20-30 times more, depending on the size of the data. For example, a `maz_size_bytes` of `750000` might result in OPA using around `18750000` bytes of memory space. You can use `pprof` to monitor usage for your particular use case.
```
Comment (ashutosh-narkar) [inline docs/content/configuration.md:551]: Let's file an issue for this and get that resolved asap. We can remove this comment or add a note in the docs.

File: docs/content/configuration.md [hunk 8]
```diff
@@ -548,7 +548,7 @@ The following signing algorithms are supported:
 
 ### Caching
 
-Caching represents the configuration of the inter-query cache that built-in functions can utilize.
+Caching represents the configuration of the inter-query cache that built-in functions can utilize. Note: There is a [known issue](https://github.com/open-policy-agent/opa/issues/3042) with how the cache calculates memory usage, resulting in more memory usage than expected.
```
Comment (ashutosh-narkar) [inline docs/content/configuration.md:551]: Can we just remove this as we are going to address the issue shortly.

**Review by ashutosh-narkar — COMMENTED** [review]
@gshively11 these changes look good ! I just had couple of comments and we can then merge:

* Let's close #2978 once #3042 is addressed. I think your commit message will close #2978.
* Can we add a lifecycle test in `plugins/discovery/discovery_test.go` that would exercise the new feature ?

File: docs/content/configuration.md (hunk 8 above)
Comment (gshively11) [reply docs/content/configuration.md:551]: We can if you insist, but I kept it on the off chance that it saves someone days of hair pulling (I wish I had seen that note 😄 ).

**Review by ashutosh-narkar — APPROVED** [review]
LGTM
