### PR TITLE
plugins/logs: fixed reconfiguration race condition

### LINKED ISSUE #2835: logging panic under load test with unix domain socket
We are running opa envoy plugin with Istio authz. We have EnvoyFilter connects to opa plugin over Unix Domain Socket.
When we run load test we faced with panic.

## Expected Behavior

Prints decision logs without error.

## Actual Behavior

We faced with panic error.

## Steps to Reproduce the Problem

OPA Plugin args:

`{
		"run",
		"--server",
		"--set=services.bundle.url=" + bundleAPIUrl,
		"--set=bundles.authz.service=bundle",
		"--set=bundles.authz.resource=" + policyPath,
		"--set=bundles.authz.polling.min_delay_seconds=60",
		"--set=bundles.authz.polling.max_delay_seconds=120",
		"--set=plugins.envoy_ext_authz_grpc.addr=unix:///sock/opa-envoy.sock",
		"--set=plugins.envoy_ext_authz_grpc.path=" + defaultDecision,
		"--set=decision_logs.console=true",
	}`

## Additional Info

`authz-agent panic: runtime error: invalid memory address or nil pointer dereference                                                                          │
│ authz-agent [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb1e44e]                                                                           ││ authz-agent goroutine 203286 [running]:                                                                                                                      ││ authz-agent github.com/open-policy-agent/opa-envoy-plugin/vendor/github.com/open-policy-agent/opa/plugins/logs.(*Plugin).maskEvent(0xc000158fd0, 0xf6b980, 0 │
│ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/vendor/github.com/open-policy-agent/opa/plugins/logs/plugin.go:661 +0 ││ authz-agent github.com/open-policy-agent/opa-envoy-plugin/vendor/github.com/open-policy-agent/opa/plugins/logs.(*Plugin).Log(0xc000158fd0, 0xf6b980, 0xc0009 ││ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/vendor/github.com/open-policy-agent/opa/plugins/logs/plugin.go:440 +0 │
│ authz-agent github.com/open-policy-agent/opa-envoy-plugin/internal.(*envoyExtAuthzGrpcServer).log(0xc00013e800, 0xf6b980, 0xc00099f0e0, 0xcdf2e0, 0xc0007715 ││ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/internal/internal.go:458 +0x25e                                       ││ authz-agent github.com/open-policy-agent/opa-envoy-plugin/internal.(*envoyExtAuthzGrpcServer).Check.func1(0xc000575840, 0xc00013e800, 0xf6b980, 0xc00099f0e0 │
│ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/internal/internal.go:216 +0xcb                                        ││ authz-agent github.com/open-policy-agent/opa-envoy-plugin/internal.(*envoyExtAuthzGrpcServer).Check(0xc00013e800, 0xf6b980, 0xc00099f0e0, 0xc00099f110, 0xc0 ││ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/internal/internal.go:343 +0x9a6                                       │
│ authz-agent github.com/open-policy-agent/opa-envoy-plugin/vendor/github.com/envoyproxy/go-control-plane/envoy/service/auth/v2._Authorization_Check_Handler(0 ││ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/vendor/github.com/envoyproxy/go-control-plane/envoy/service/auth/v2/e ││ authz-agent github.com/open-policy-agent/opa-envoy-plugin/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001358c0, 0xf735a0, 0xc000c24600, 0xc0 │
│ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/vendor/google.golang.org/grpc/server.go:995 +0x460                    ││ authz-agent github.com/open-policy-agent/opa-envoy-plugin/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0001358c0, 0xf735a0, 0xc000c24600, 0xc0001 ││ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/vendor/google.golang.org/grpc/server.go:1275 +0xd3d                   │
│ authz-agent github.com/open-policy-agent/opa-envoy-plugin/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000504040, 0xc0001358c0, 0xf735a0, ││ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/vendor/google.golang.org/grpc/server.go:710 +0xa1                     ││ authz-agent created by github.com/open-policy-agent/opa-envoy-plugin/vendor/google.golang.org/grpc.(*Server).serveStreams.func1                              │
│ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/vendor/google.golang.org/grpc/server.go:708 +0xa1                     ││ authz-agent stream closed                                                                                                                                    ││`

image

### PR DESCRIPTION
**Pull request by kubaj**
# Bug summary

Logging plugin had race condition while it was masking the log and plugin was reconfigured at the same time. This caused panic of the OPA. Fixed issue for us and also may fix #2835 .

# Details

Masking part of the logging plugin had incorrectly placed mutex -- only
for writing the variable p.mask, but not for reading it. This caused
race condition in the situation when bundle update calls plugin.Reconfigure()
method between setting the p.mask variable and then evaluating it.
Reconfiguration of the plugin sets p.mask to nil and therefore calling
p.mask.Eval() results in panic.

Tests covering functionality shouldn't change, test covering the fixed issue is not delivered, because it's difficult to write a test simulating the race condition (if you know about some efficient way, feel free to guide me, I'll happily learn).

### CODE REVIEW

File: plugins/logs/plugin.go [hunk 1]
```diff
@@ -675,29 +680,20 @@ func (p *Plugin) maskEvent(ctx context.Context, txn storage.Transaction, event *
...
-	if err != nil {
-		return err
-	}
-
-	rs, err := p.mask.Eval(
-		ctx,
-		rego.EvalParsedInput(input),
-		rego.EvalTransaction(txn),
-	)
+		return rs, err
```
Comment (tsandall) [inline plugins/logs/plugin.go:695]: Instead of evaluating the mask policy while holding the mutex, assign the value of `p.mask` to a local variable and then release the mutex. We don't want to hold the mutex while evaluating the mask policy.

**Review by tsandall — COMMENTED** [review]
Nice find! See my comment about only grabbing the mask while holding the mutex.

**Comment by kubaj** [comment]
I updated the PR.

**Review by srenatus — APPROVED** [review]
👏 Good find, thank you!

**Comment by kubaj** [comment]
@srenatus, I'm glad I could help. I squashed commits according to instructions, can you reapprove please so I can merge?

**Review by tsandall — APPROVED** [review]
LGTM

**Comment by ashutosh-narkar** [comment]
@kubaj Can you please squash the commits and update the commit message ? The sign-off line is duplicated.

**Comment by kubaj** [comment]
@ashutosh-narkar I updated the commit message to remove duplicate sign-off. I hope it's all you need.

**Comment by ashutosh-narkar** [comment]
@kubaj thanks for updating your commit message. I think you'll need to rebase from master and then push your single commit to your fork as currently it's showing that 11 commits need to be merged.

**Comment by kubaj** [comment]
@ashutosh-narkar sorry about that. I fixed that, it should be ok now.

**Review by srenatus — APPROVED** [review]
Thanks! 🎉
