### PR TITLE
Fix OpenTelemetry graceful shutdown.

### LINKED ISSUE #6651: Failed to shutdown OpenTelemetry trace exporter gracefully.
## Short description 

When running OPA with the distributed tracing option enabled, we get the following error when the server is stopped.

```
Failed to shutdown `OpenTelemetry` trace exporter gracefully.
```

## Steps To Reproduce
1. Get the latest version of `opa` (I've tried with version 0.62 and the latest version)
```
./opa_linux_amd64 version
Version: 0.63.0-dev
Build Commit: d3a4a87f506dec744ed93177c37bea5e2afa186b
Build Timestamp: 2024-03-27T19:08:00Z
Build Hostname: nico-Latitude-7420
Go Version: go1.21.0
Platform: linux/amd64
WebAssembly: available
```
3. Run the following command line 
```
./opa_linux_amd64 run --server --set distributed_tracing.type=grpc
```
5. Kill the process (Ctrl + C works fine)
6. The full output should looks like that
```
./opa_linux_amd64 run --server --set distributed_tracing.type=grpc
{"addrs":[":8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server. OPA is running on a public (0.0.0.0) network interface. Unless you intend to expose OPA outside of the host, binding to the localhost interface (--addr localhost:8181) is recommended. See https://www.openpolicyagent.org/docs/latest/security/#interface-binding","time":"2024-03-28T09:18:37+01:00"}
^C{"level":"info","msg":"Shutting down...","time":"2024-03-28T09:18:38+01:00"}
{"level":"info","msg":"Server shutdown.","time":"2024-03-28T09:18:38+01:00"}
{"err":"context canceled","level":"error","msg":"Failed to shutdown OpenTelemetry trace exporter gracefully.","time":"2024-03-28T09:18:38+01:00"}
```

## Expected behavior

The `OpenTelemetry` trace exporter should be gracefully shut down, and no error should be seen.   

## Additional context

We have seen this error appeared after upgrading OPA from version 0.59 to 0.62.

### PR DESCRIPTION
**Pull request by David-Wobrock**
### Why the changes in this PR are needed?

When running OPA with the distributed tracing option enabled, the OpenTelemetry trace exporter is not gracefully shut down when the server is stopped.

### What are the changes in this PR?

This PR fixes that issues by moving the trace exporter shutdown in the gracefulServerShutdown function.

### Notes to assist PR review:

Picked up from https://github.com/open-policy-agent/opa/pull/6664

### Further comments:

Fixes #6651.
This bug seems to have been introduced by this [commit](https://github.com/open-policy-agent/opa/commit/f063c90275bed61c4381db771162724e191f2d3c).

### CODE REVIEW

**Review by ashutosh-narkar — COMMENTED** [review]
@David-Wobrock the change looks good. Just one comment on the test.

**Comment by David-Wobrock** [comment]
Thanks for the review @ashutosh-narkar 🙏 

I pushed the edits. Let me know if I can do further changes :)

File: runtime/runtime_test.go [hunk 1]
```diff
@@ -1235,6 +1235,46 @@ func TestServerInitializedWithBundleRegoVersion(t *testing.T) {
...
+		}
+
+		done := make(chan struct{})
+		go func() {
+			rt.StartServer(ctx)
+			close(done)
+		}()
+		<-done
+
+		expected := "Failed to shutdown OpenTelemetry trace exporter gracefully."
```
Comment (ashutosh-narkar) [inline runtime/runtime_test.go:1271]: Can we also have a test where the trace exporter does not shutdown gracefully?

Comment (David-Wobrock) [reply runtime/runtime_test.go:1271]: I guess the variable is misnamed, since we _don't_ expected this message to be present in the logs - and thus test that the trace exporter did shutdown gracefully.

But anyway, I wouldn't know how to write a test where the trace exporter doesn't shutdown gracefully 😕 

I'd need some help here :)
Or we could add such a test in a later PR, and start with this fix for now.

Comment (ashutosh-narkar) [reply runtime/runtime_test.go:1271]: Sure we can do that.

**Review by ashutosh-narkar — APPROVED** [review]
