### PR TITLE
compile: Add support for unknowns other than input

### LINKED ISSUE #2581: opa build: allow for declaring extra unknowns (for optimization)
## Expected Behavior

During bundle optimization, references that are outside of the bundle will fail.

Concretely, if we had policy code that's depending on some other piece of data, say, `data.auth.jwks`(which will be provided by means different from the bundle built), the optimized bundle should still reference `data.auth.jwks`.

## Actual Behavior

The optimization finds `data.auth.jwks` undefined and proceeds killing branches accordingly.

## Steps to Reproduce the Problem

With `policy/authz.rego` as

```rego
package authz

default allow = false
allow {
	data.auth.authenticated
}
```

and running `opa build -O 1 -e authz/allow policy/authz.rego`, we find

```console
$ tar xvfO bundle.tar.gz /optimized/authz.rego
tar: Removing leading '/' from member names
x optimized/authz.regopackage authz

allow = __result__ {
        __result__ = false
}
$
```

The expected optimized policy would be something like

```rego
allow = __result__ {
	data.auth.authenticated
        __result__ = true
}
```

* OPA 0.22.0

## Some options

I believe we could expose an `--unknown` flag (that can be specified multiple times) to feed further unknowns into the compiler.

**Alternatively**, it maybe be worth exploring if _any data not part of this bundle_ should automatically be declared _unknown_. I think this might be nicer to work with, albeit more difficult to implement. 🤔

### PR DESCRIPTION
**Pull request by tsandall**
Previously the build command and the compile package would only mark
input as unknown. If documents under data needed to be treated as
unknown, there was no solution. This commit updates the compile
package to infer unknowns based on the bundle roots. If the policy
refers to a data document _outside_ of one of the bundle roots, that
data document will be marked as unknown during optimization/partial
eval.

Fixes #2581

Signed-off-by: Torin Sandall <torinsandall@gmail.com>

### CODE REVIEW

**Comment by tsandall** [comment]
cc @srenatus

File: compile/compile.go [hunk 1]
```diff
@@ -697,3 +733,67 @@ func (ss orderedStringSet) Append(s ...string) orderedStringSet {
...
+}
+
+// ContainsPrefix returns true if r is prefixed by any of the existing refs in the set.
+func (rs *refSet) ContainsPrefix(r ast.Ref) bool {
+	return rs.s.Until(func(x *ast.Term) bool {
+		exist := x.Value.(ast.Ref)
+		if r.HasPrefix(exist) {
+			return true
+		}
+		return false
```
Comment (srenatus) [inline compile/compile.go:764]: [nit] 
```suggestion
		return r.HasPrefix(exist)
```

File: compile/compile.go [hunk 2]
```diff
@@ -697,3 +733,67 @@ func (ss orderedStringSet) Append(s ...string) orderedStringSet {
...
+	for i := range x {
+		result.AddPrefix(x[i])
+	}
+	return result
+}
+
+// ContainsPrefix returns true if r is prefixed by any of the existing refs in the set.
+func (rs *refSet) ContainsPrefix(r ast.Ref) bool {
+	return rs.s.Until(func(x *ast.Term) bool {
+		exist := x.Value.(ast.Ref)
```
Comment (srenatus) [inline compile/compile.go:760]: This cast can't fail, I suppose...?

Comment (tsandall) [reply compile/compile.go]: Correct...however, I just realized this could be implemented simply on top of a slice. No need to use ast.Set here. That avoids the need to type assert. Thanks!

File: compile/compile.go (hunk 1 above)
Comment (tsandall) [reply compile/compile.go]: Fixed.
