### PR TITLE
Use unique query paths and module id's for partial eval in the server

### LINKED ISSUE #2247: OPA server can return result for wrong query when using `?partial`
# Expected Behavior
Starting up the server with some test policies:

`policy.rego`
```rego
package example_rbac

default allow = false

allow {
    user_has_role[role_name]
    role_has_permission[role_name]
}

user_has_role[role_name] {
    role_binding = data.bindings[_]
    role_binding.role = role_name
    role_binding.user = input.subject.user
}

role_has_permission[role_name] {
    role = data.roles[_]
    role.name = role_name
    role.operation = input.action.operation
    role.resource = input.action.resource
}
```
`data.json`
```json
{
    "roles": [
        {
            "operation": "read",
            "resource": "widgets",
            "name": "widget-reader"
        },
        {
            "operation": "write",
            "resource": "widgets",
            "name": "widget-writer"
        }
    ],
    "bindings": [
        {
            "user": "inspector-alice",
            "role": "widget-reader"
        },
        {
            "user": "maker-bob",
            "role": "widget-writer"
        }
    ]
}
```

```
opa run -s ./data.json ./policy.rego
```

I should then be able to make multiple queries to the server with them affecting the results of each other:

`input.json`
```
{
  "input": {
    "subject": {
      "user": "maker-bob"
    },
    "action": {
      "resource": "widgets",
      "operation": "write"
    }
  }
}
```
First query for `allow`
```
{15:50} ✘ /tmp ❯ curl -X POST -d "@input.json" 'http://localhost:8181/v1/data/example_rbac/allow'
{"result":true}%
```
Now for `user_has_role`
```
{15:50} /tmp ❯ curl -X POST -d "@input.json" 'http://localhost:8181/v1/data/example_rbac/user_has_role'
{"result":["widget-writer"]}%
```
Back to `allow`
```
{15:50} /tmp ❯ curl -X POST -d "@input.json" 'http://localhost:8181/v1/data/example_rbac/allow'
{"result":true}%
```
🎉 
Success!

I should then be able to do the same thing with `?partial`
# Actual Behavior
The response I get back for any cached `?partial` query is the result of the last one to have been partially evaluated:
First query for `allow`
```
{15:50} /tmp ❯ curl -X POST -d "@input.json" 'http://localhost:8181/v1/data/example_rbac/allow?partial'
{"result":true}%
```
Now for `user_has_role`
```
{15:51} /tmp ❯ curl -X POST -d "@input.json" 'http://localhost:8181/v1/data/example_rbac/user_has_role?partial'
{"result":["widget-writer"]}%
```
Back to `allow`
```
{15:51} /tmp ❯ curl -X POST -d "@input.json" 'http://localhost:8181/v1/data/example_rbac/allow?partial'
{"result":["widget-writer"]}%
```
🤔 

# Additional Info
It looks like the problem is that we share a compiler for all of the cached partially evaluated rego's and each time we do the partial evaluation we store the freshly generated module on the compiler with id `__partialresult__` and the same `data.partial.__result__` query. Now when _any_ subsequent evaluations occur for a cached partial query path we end up using that same module, regardless of whether or not it was actually the partial module associated with the query path originally.

### PR DESCRIPTION
**Pull request by patrick-east**
This is a combination of two changes to fix #2247 

First up we change the way that `rego.Rego` objects generate the partial result modules on the compiler. We will name them with more dynamic module id's so that >1 query can be partially evaluated sharing the same compiler.

Next we adjust the OPA server to specify a namespace when doing partial evaluation so that cached results have unique query paths.

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -2038,12 +2039,27 @@ func (s *Server) getCompiler() *ast.Compiler {
...
+		rego.Tracer(tracer),
+		rego.Instrument(instrument),
+		rego.Runtime(s.runtime),
+		rego.UnsafeBuiltins(unsafeBuiltinsMap),
+	)
+
 	if partial {
+		// pick a namespace for the query (path), doesn't really matter what it is
+		// as long as it is unique for each path.
+		namespace := fmt.Sprintf("partial_%d", xxhash.ChecksumString64(path))
```
Comment (tsandall) [inline server/server.go:2057]: What happens if we use the path as the partial namespace without hashing it?

File: rego/rego.go [hunk 2]
```diff
@@ -1645,9 +1645,10 @@ func (r *Rego) partialResult(ctx context.Context, pCfg *PrepareConfig) (PartialR
 	}
 
 	// Update compiler with partial evaluation output.
-	r.compiler.Modules["__partialresult__"] = module
+	id := fmt.Sprintf("__partialresult__%s__", ectx.partialNamespace)
+	r.compiler.Modules[id] = module
 	for i, module := range pq.Support {
-		r.compiler.Modules[fmt.Sprintf("__partialsupport%d__", i)] = module
+		r.compiler.Modules[fmt.Sprintf("__partialsupport__%s__%d__", ectx.partialNamespace, i)] = module
```
Comment (tsandall) [inline rego/rego.go:1651]: I'm now wondering whether we should be doing this at all...this clearly fixes the issue but I'm questioning whether the rego package should modify the compiler it's been given. Perhaps we should start considering a `regov2` package. Just a thought.

File: server/server.go (hunk 1 above)
Comment (patrick-east) [reply server/server.go:2057]: We can, we just need to transform it into something that is a valid `Var` string. I was less concerned about collisions since I think in practice people don't use a huge variety of queries (this issue itself was only noticed while reading through the code debugging something else).

I'll take a look at just converting them into safe var strings from the path. I agree that its the safest option.

File: rego/rego.go (hunk 2 above)
Comment (patrick-east) [reply rego/rego.go:1651]: +100

I think its a nice user experience when you are not managing the compiler external to the `Rego` objects. Would definitely want to rethink some of this longer term.

File: server/server.go (hunk 1 above)
Comment (tsandall) [reply server/server.go:2057]: Can the namespace just be something like `partial["<path>"]`?

Comment (patrick-east) [reply server/server.go:2057]: 💡 probably, yea

Its used as the module ID, which can be any string, and as part of the package name so that should be OK (we can just like "%q" the path or something when sticking it in there)

Comment (patrick-east) [reply server/server.go]: Latest version just uses the url path, and I relaxed the check on the partial namespace so as long as its a valid package name its OK.
