### PR TITLE
fix: returns error with illegal args with unknowns flag (#7127)

### LINKED ISSUE #7127: opa eval: panic when given bad input for --unknowns
`opa eval --help` says

```
-u, --unknowns stringArray                                      set paths to treat as unknown during partial evaluation (default [input])
```

so it's not completely out of the question to try setting it to `[input,data.posts]`. When you get then is a panic:

```
% opa eval --partial -d q.rego -fpretty -u '[input,data.posts]' data.example.allow
panic: illegal value

goroutine 1 [running]:
github.com/open-policy-agent/opa/topdown.newSaveSetElem(...)
	/Users/stephan/Sources/open-policy-agent/opa/topdown/save.go:132
github.com/open-policy-agent/opa/topdown.(*saveSet).Push(0xc0000177a0, {0xc000135c20, 0x1, 0x100071205?}, 0xc000020180)
	/Users/stephan/Sources/open-policy-agent/opa/topdown/save.go:31 +0x434
github.com/open-policy-agent/opa/topdown.newSaveSet({0xc000135c20, 0x1, 0x1}, 0xc000020180, 0x0)
	/Users/stephan/Sources/open-policy-agent/opa/topdown/save.go:26 +0xbb
github.com/open-policy-agent/opa/topdown.(*Query).PartialRun(0xc000425180, {0x101f32350, 0x102a8b840})
	/Users/stephan/Sources/open-policy-agent/opa/topdown/query.go:370 +0x72e
github.com/open-policy-agent/opa/rego.(*Rego).partial(0xc0003c6e08, {0x101f32350, 0x102a8b840}, 0xc000365860)
	/Users/stephan/Sources/open-policy-agent/opa/rego/rego.go:2455 +0x93c
github.com/open-policy-agent/opa/rego.PreparedPartialQuery.Partial({{0xc0003c6e08?, 0xc0004034d0?}}, {0x101f32350, 0x102a8b840}, {0xc000445c90?, 0xc0000d98c0?, 0x1035df108?})
	/Users/stephan/Sources/open-policy-agent/opa/rego/rego.go:507 +0x149
github.com/open-policy-agent/opa/cmd.evalOnce({0x101f32350, 0x102a8b840}, 0xc0001bd200)
	/Users/stephan/Sources/open-policy-agent/opa/cmd/eval.go:472 +0xf07
github.com/open-policy-agent/opa/cmd.eval({_, _, _}, {0xc000402a50, 0x0, 0x1, {0xc000444e30, 0x1, 0x1}, {0x102a8b840, ...}, ...}, ...)
	/Users/stephan/Sources/open-policy-agent/opa/cmd/eval.go:374 +0x3f0
github.com/open-policy-agent/opa/cmd.init.5.func2(0xc0003f2f08?, {0xc000376380?, 0x4?, 0x1019e5a41?})
	/Users/stephan/Sources/open-policy-agent/opa/cmd/eval.go:292 +0x6e
github.com/spf13/cobra.(*Command).execute(0xc0003f2f08, {0xc000376310, 0x7, 0x7})
	/Users/stephan/Sources/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x102a4cc80)
	/Users/stephan/Sources/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0xc0000061c0?)
	/Users/stephan/Sources/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:1041 +0x13
main.main()
	/Users/stephan/Sources/open-policy-agent/opa/main.go:14 +0x1a
```

It would be nicer if we told the user that their argument to `--unknowns` is of the wrong type.

(BTW the right format would be `--unknowns input --unknowns data.posts`)

### PR DESCRIPTION
**Pull request by kd-labs**
### Why the changes in this PR are needed?

- This fixes #7127 when multiple unknowns are passed as array to unknowns flag

### What are the changes in this PR?

- We are doing a regex match for the presence of array in the argument passed to unknowns flag. If it matches with array then we return error.

### CODE REVIEW

File: cmd/eval.go [hunk 1]
```diff
@@ -132,6 +138,14 @@ func validateEvalParams(p *evalCommandParams, cmdArgs []string) error {
...
 	}
 
+	//* check if illegal arguments is passed with unknowns flag
+	regexArr := regexp.MustCompile(`^\[.*\]$`)
+	for _, unknwn := range p.unknowns {
+		if regexArr.MatchString(unknwn) {
+			return errors.New(errIllegalUnknownsArg.Error())
+		}
+	}
+
```
Comment (srenatus) [inline cmd/eval.go:148]: I wonder if we can attempt to parse it using [`ast.ParseTerm`](https://pkg.go.dev/github.com/open-policy-agent/opa/ast#ParseTerm), like
```go
t, err := ast.ParseTerm(unknwn)
if err != nil { ... }
```
and then check `t.Value`'s type, like
```go
switch t.Value.(type) {
case ast.Ref: // OK
default:
  return errors.New(errIllegalUnknownsArg.Error())
}
```

That way, we should be able to capture _more illegal inputs_ than using the regexp. For example, proficient rego users _could_ attempt to pass a _set_ of things like `{data.unknown, input.foobar}` using `{..}` which isn't captured by the regular expression.

**Review by srenatus — COMMENTED** [review]
Thanks for looking into this! It's got the right shape, I'm just wondering if we could attempt to _parse_ the argument, to have exactly the same guards as would happen later on 🤔  Would you be up for trying this approach?

Thanks again for contributing. 🎉

File: cmd/eval.go (hunk 1 above)
Comment (kd-labs) [reply cmd/eval.go:148]: sure...will look into it

File: cmd/eval_test.go [hunk 2]
```diff
@@ -29,6 +29,50 @@ import (
...
+	tests := []struct {
+		name        string
+		unknowns    string
+		expectedErr error
+	}{
+		{
+			name:        "happy path: passing ref as unknown",
+			unknowns:    "data.posts",
+			expectedErr: nil,
+		},
```
Comment (srenatus) [inline cmd/eval_test.go:43]: Please, could you add cases for these?
- `input`
- `input.users`
just to be sure that it'll all end up a ref.

**Review by srenatus — COMMENTED** [review]
Thank you! Just one small ask for the tests. This is a nice contribution 👏

File: cmd/eval.go [hunk 3]
```diff
@@ -132,6 +137,21 @@ func validateEvalParams(p *evalCommandParams, cmdArgs []string) error {
 		return errors.New("invalid output format for evaluation")
 	}
 
+	//* check if illegal arguments is passed with unknowns flag
```
Comment (srenatus) [inline cmd/eval.go:140]: [nit]
```suggestion
	// check if illegal arguments is passed with unknowns flag
```

File: cmd/eval_test.go (hunk 2 above)
Comment (kd-labs) [reply cmd/eval_test.go:43]: I've made the required changes in the test cases. could you plz review

File: cmd/eval.go (hunk 1 above)
Comment (kd-labs) [reply cmd/eval.go]: done

File: cmd/eval.go [hunk 4]
```diff
@@ -132,6 +137,21 @@ func validateEvalParams(p *evalCommandParams, cmdArgs []string) error {
...
+		term, err := ast.ParseTerm(unknwn)
+		if err != nil {
+			return err
+		}
+
+		switch term.Value.(type) {
+		case ast.Ref:
+			return nil
+		default:
+			return errors.New(errIllegalUnknownsArg.Error())
```
[the remark this answers is not in the document]
Comment (kd-labs) [reply cmd/eval.go]: done

File: cmd/eval.go (hunk 3 above)
Comment (kd-labs) [reply cmd/eval.go]: done

**Review by srenatus — APPROVED** [review]
LGTM thanks!
