### PR TITLE
Ignore keys of unknown alg when verifying JWTs with JWKS

### LINKED ISSUE #4699: JWKS Uri containing an encryption key (besides signature keys) will fail io.jwt.decode_verify
## Short description 
We use Keycloak, and it was configured to also have an encryption key exposed on the JWKS URI, using an algorithm that OPA does not support. OPA fails, but you cannot easily see that if you do not use the `--strict-builtin-errors` flag, which is not set on the Rego playground at https://play.openpolicyagent.org/.

OPA should ignore keys it does not support instead of failing, offer options for filtering, or better document that behaviour. In the above case, it's enough to only feed signature keys to `io.jwt.decode_verify`.

* OPA version: 0.40.0-envoy-1
* used in k8s, together with istio external authorization, but the issue also is there in the playground and locally

## Steps To Reproduce

Use a JWKS like this:

```json
{
  "keys": [
    {
      "kid": "DsmD8hx6.....Z_ThSPY",
      "kty": "RSA",
      "alg": "RS256",
      "use": "sig",
      "n": "iVJfdNtA7wiT91cnG3uDrq80akzb0nm5q.....5Bw1ij5FyHULUnCRXXZeXZKYNZx08fr1T1q4Dvw",
      "e": "AQAB",
      "x5c": [
        "MIICnTCCAYUCBgGAmcGzvzANBgkqh.....zqnm8BWAH3zR6Ho7Cxghf63i79o1MDZ2S0DNTXg8Rw=="
      ],
      "x5t": "C1Qht.....ZaY72S4",
      "x5t#S256": "4KN412_TA.....xXpnFgpWJ8"
    },
    {
      "kid": "tRA344j.....Bau2GII",
      "kty": "RSA",
      "alg": "RSA-OAEP",
      "use": "enc",
      "n": "onlqv4UZx5ZabJ3TCq-IO0s0xaOwo6fWl9o4SzLXPbG.....tvxonQhoYOeMlS0XkdEdLzB-eqh_hkQ",
      "e": "AQAB",
      "x5c": [
        "MIICnTCCAYUCBgGAmcG0xjANBgkqhkiG9w0BAQsFADASMRAwDgYDVQ.....Q2YVaQn47Eew=="
      ],
      "x5t": "WKfdwb.....dQkg",
      "x5t#S256": "2_FidAw.....jlCQl20"
    }
  ]
}
```
Call `io.jwt.decode_verify` as described in the example from https://www.openpolicyagent.org/docs/v0.39.0/policy-reference/#using-jwks :

```
jwks = `{
    "keys": [{
        "kty":"EC",
        "crv":"P-256",
        "x":"z8J91ghFy5o6f2xZ4g8LsLH7u2wEpT2ntj8loahnlsE",
        "y":"7bdeXLH61KrGWRdh7ilnbcGQACxykaPKfmBccTHIOUo"
    }]
}`
token = "some_JWT_token"

[valid, header, payload] := io.jwt.decode_verify(token, {
    "cert": jwks,
    "iss": "xxx",
})
```
-> OPA fails to validate the token, even if it is signed with the key OPA supports.

## Expected behavior
* OPA should ignore keys it does not support, or at least offer options to filter for signature keys only.
* The OPA playground should either run with `--strict-builtin-errors` by default (any reason not to?), or at least offer an option to enable that

We implemented this manually via this code (for others to use):
```
jwks_request(url) = http.send({
      "url": url,
      "method": "GET",
      "force_cache": true,
      "force_cache_duration_seconds": 3600 # Cache response for an hour
})

jwks := jwks_request("YOUR_JWKS_URI").raw_body
filtered_jwks := [ key |
      keys := json.unmarshal(jwks)["keys"]
      key := keys[_]
      key["use"] == "sig"
    ]
compatible_jwks := json.marshal({"keys": filtered_jwks})
```

## Additional context
We did not configure our keycloak to explicitly contain an encryption key in the JWKS endpoint - we're using a SaaS provider, and that was the default configuration over there.

### PR DESCRIPTION
**Pull request by anderseknert**
Additionally, improve the JWT verification process when a JWKS
is provided:

* If `kid` is present in JWT header, and exists in JWKS — verify using
  that key only.
* If `kid` not present in JWT header, try verification only using keys
  matching the `alg` provided in the JWT header (mandatory claim).

Fixes #4699

Signed-off-by: Anders Eknert <anders@eknert.com>

### CODE REVIEW

File: topdown/tokens.go [hunk 1]
```diff
@@ -336,14 +356,45 @@ func builtinJWTVerify(a ast.Value, b ast.Value, hasher func() hash.Hash, verify
...
+		} else {
+			if header.alg != key.alg {
+				continue
+			}
+			err = verify(key.key, getInputSHA([]byte(token.header+"."+token.payload), hasher), []byte(signature))
+			if err == nil {
+				return ast.Boolean(true), nil
+			}
 		}
 	}
```
Comment (johanfylling) [inline topdown/tokens.go:399]: Should we consider also skipping any key here that has a `kid` that doesn't match the `kid` of the JWT?
This would step outside the realm of just being an optimization; but it might be the correct thing to do ..

File: topdown/tokens_test.go [hunk 2]
```diff
@@ -496,3 +497,205 @@ func TestTopdownJWTEncodeSignECWithSeedReturnsSameSignature(t *testing.T) {
 		}
 	}
 }
+
+func TestTopdownJWTUnknownAlgTypesDiscardedFromJWKS(t *testing.T) {
+	cert := `{
```
Comment (johanfylling) [inline topdown/tokens_test.go:502]: Technically a JWK Set ;p

**Review by johanfylling — APPROVED** [review]
LGTM 👍

**Comment by anderseknert** [comment]
> The ticket also has a request for improved documentation. At the very least, we should document this new behavior.

If I understand the conversation between @lenalebt and @srenatus correctly, the suggested update to the docs would be to change the example not to use the raw body (i.e. string) representation of the JWKS, but to rather hack around the issue (fixed by this) by unmarshalling the JWKS, filter out the non-parseable key(s), and then marshall it back into a new JWKS to use for validation. The documented solution is AFAICS the correct one.

File: topdown/tokens.go (hunk 1 above)
Comment (johanfylling) [reply topdown/tokens.go:399]: We would still try keys without `kid`, though. 
They'd have broken JWT verification if they expect to use a key that has a different `kid` than the JWT. But yes, this would be a change in behavior; which may be frowned upon.

**Review by johanfylling — APPROVED** [review]

File: topdown/tokens.go (hunk 1 above)
Comment (anderseknert) [reply topdown/tokens.go:399]: Ah, I see what you mean. Yeah we probably _should_ do that at some point. Might be a good idea to have an `opa1.0`-labeled ticket for everything around JWT, JWKS and certificates (also in the OPA configuration) which would be good fixes but probably not worth doing in a minor release.
