### PR TITLE
planner: adjust check introduced in #5839

### LINKED ISSUE #5964: CallDynamic regression
`opa eval` and `opa eval -t wasm` differ for

```rego
# x.rego
package x
import future.keywords.if

foo.bar.allow if f(7)
foo.baz.allow if f(8)
qux.corge.allow if f(-1)

f(_) if true
```

and 
```rego
# y.rego
package y
import future.keywords.if

static if data.x.foo.bar.allow

dd1 if data.x[input.a].bar.allow

dd2 if data.x[input.a][input.b].allow
```

When evaluating `data.y` with input as `{"a": "foo", "b": "bar"}`, `opa eval -d x.rego -d y.rego -i input.json -f pretty data.y` yields
```json
{
  "static": true,
  "dd1": true,
  "dd2": true
}
```
whereas adding `-t wasm` only yields
```json
{
  "static": true
}
```
Probably related to https://github.com/open-policy-agent/opa/pull/5839

### PR DESCRIPTION
**Pull request by srenatus**
So the check introduced before was too broad: it aborted optimizations at the wrong spot -- the resulting plan didn't add up: path lengths used in CallDynamicStmt didn't match path lengths that the planned funcs had.

So, while this change looks like over-fitting (also to me), we're really trying to make test previous fix more specific.

Generally looking at that section of the planner, it feels like the intro of general refs would be a good moment to nuke and start over: the way that refs-with-vars are put into the ruletrie seems like the root cause of our trouble here.

Fixes #5964.

### CODE REVIEW

File: internal/planner/planner.go [hunk 1]
```diff
@@ -2286,10 +2286,28 @@ outer:
...
+		// We want to capture this situation:
+		//   a.b[c] := "x" if c := "c"
+		//   a.b.d := "y"
+		//
+		// Not this:
+		//   a.b[c] := "x" if c := "c"
+		//   a.d := "y"
+		// since the length doesn't add up. Even if input.x was "d", the second
+		// rule (a.d) wouldn't contribute anything to the result, since we cannot
+		// "dot it".
```
Comment (srenatus) [inline internal/planner/planner.go:2300]: We're leaning a bit onto the compiler's restrictions wrt overlapping rules here... it's also a bit of a mess 😬

**Review by ashutosh-narkar — APPROVED** [review]
