### PR TITLE
downloader: log message on unexpected bundle content type

### LINKED ISSUE #4278: Improve error message when bundle server doesn't serve a bundle
When pointing OPA to fetch bundles from an endpoint that doesn't serve bundles (likely due to typo or misconfiguration in the remote), the error message looks like this:
```
{"level":"error","msg":"Bundle load failed: bundle read failed: archive read failed: gzip: invalid header","name":"authz","plugin":"bundle","time":"2022-01-25T06:28:49Z"}
```
This has led many users to believe there is something wrong with the bundle packaging itself, leading them to debug the bundle creation process, when the real problem is that the remote doesn't serve the bundle in the first place.

It would be good if we printed this error message only when a broken bundle was served. If we can't differentiate, we might want to print just something like "no bundle found at remote or invalid bundle format".

### PR DESCRIPTION
**Pull request by anderseknert**
Fixes #4278

Signed-off-by: Anders Eknert <anders@eknert.com>

### CODE REVIEW

**Comment by anderseknert** [comment]
Not sure if debug is the right log level, but since a wrong content-type header _could_ be used to serve a valid bundle, it would likely be noisy to log this at higher levels.

File: download/download.go [hunk 1]
```diff
@@ -311,6 +311,23 @@ func (d *Downloader) download(ctx context.Context, m metrics.Metrics) (*download
 			if d.sizeLimitBytes != nil {
 				reader = reader.WithSizeLimitBytes(*d.sizeLimitBytes)
 			}
+
+			if d.logger.GetLevel() <= logging.Debug {
```
Comment (srenatus) [inline download/download.go:315]: I'm not sure I understand the `<=` here. Is Info <= Debug? If so, I'd expect a `>=`, so that the message is only logged when the level actually _is_ debug or more. (We don't have a higher level, though, do we? 🤔 )

File: download/download_test.go [hunk 2]
```diff
@@ -652,6 +654,53 @@ func TestOneShotNotLongPollingSwitch(t *testing.T) {
...
+		updates <- &u
+	})
+	logger := test.New()
+	logger.SetLevel(logging.Debug)
+	d.logger = logger
+
+	d.Start(ctx)
+
+	// Give time for some download events to occur
+	time.Sleep(1 * time.Second)
```
Comment (srenatus) [inline download/download_test.go:679]: What does this give us over the `u1 := <-updates` below? I'd expect the channel read to block until something has is read (i.e. something has happened). If so, the sleep here would be redundant.

File: download/download_test.go [hunk 3]
```diff
@@ -652,6 +654,53 @@ func TestOneShotNotLongPollingSwitch(t *testing.T) {
...
+
+	if !found {
+		t.Errorf("Expected log entry: %s", expectLogged)
+	}
+
+	if u1.Bundle != nil {
+		t.Fatal("expected no bundle")
+	}
+
+	d.Stop(ctx)
```
Comment (srenatus) [inline download/download_test.go:701]: These tests are often prone to race conditions. Can we Stop earlier, just to ensure that it's safe to read from `logger.Entries()`? I'd expect it to be OK to close right after L681 🤔

**Review by srenatus — APPROVED** [review]
Some nitpicks and questions but this look OK otherwise 👍

File: download/download_test.go (hunk 2 above)
Comment (anderseknert) [reply download/download_test.go:678]: This was copy-pasta from another test, and there seems to be a bunch of them following that convention. Without the sleep, these tests seem to block forever. So I guess you're right there's some race conditions going on in these tests 🙃

File: download/download_test.go (hunk 3 above)
Comment (anderseknert) [reply download/download_test.go]: Yep, moving the stop to where you suggested 👍

**Review by srenatus — APPROVED** [review]

File: download/download_test.go (hunk 2 above)
Comment (srenatus) [reply download/download_test.go:678]: Well if the race detection doesn't complain, neither will I. 😄

Comment (anderseknert) [reply download/download_test.go:678]: Apparently, it _does_ [complain](https://github.com/open-policy-agent/opa/runs/5549284478?check_suite_focus=true) 😆 Except moving the stop call to earlier, it's not really apparent to me what would make this different from other similar tests here.

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/opa/commit/a6698f78402f883a02c94f5eeec0804a44f359c9 maybe something along those lines?

File: download/download.go [hunk 4]
```diff
@@ -311,6 +311,23 @@ func (d *Downloader) download(ctx context.Context, m metrics.Metrics) (*download
 			if d.sizeLimitBytes != nil {
 				reader = reader.WithSizeLimitBytes(*d.sizeLimitBytes)
 			}
+
+			if d.logger.GetLevel() >= logging.Debug {
+				expectedBundleContentType := []string{
+					"application/gzip",
+					"application/octet-stream",
+				}
```
Comment (ashutosh-narkar) [inline download/download.go:319]: `application/vnd.openpolicyagent.bundles` is used as the content type to indicate the server supports long polling.

Comment (anderseknert) [reply download/download.go:319]: Ah, good input! I'll have that added.

**Review by srenatus — APPROVED** [review]

File: download/download_test.go (hunk 2 above)
Comment (anderseknert) [reply download/download_test.go:709]: This was fixed by removing code that wasn't necessary for these tests.

**Review by srenatus — APPROVED** [review]
