### PR TITLE
Mask rule

### LINKED ISSUE #2379: allow custom masking of fields
# Expected Behavior
Masking sensitive fields should allow the field to be mutated instead of just dropped.

# Actual Behavior
Masking only allows sensitive fields to be dropped.

# Steps to Reproduce the Problem
https://www.openpolicyagent.org/docs/v0.13.5/decision-logs/#masking-sensitive-data

Not possible to modify a field... only drop it.

# Additional Info

My use case is:
I am passing the entire JWT and other information to evaluate a decision. The JWT contains a signature that is being verified in OPA. The decision logs, however, expose the entire JWT which can be used in a playblack attack. If I drop the field, i don't have the entire context that was using for evaluating the decision. What I really want to do is just drop the JWT signature.

### PR DESCRIPTION
**Pull request by dkiser**
Fixes #2379 

This is an initial attempt at enhancing decision log masks by providing a new structured format for mask rules that allow either erasing or modifying input objects.  Backwards compatibility is maintained with the original mask rule format.

### CODE REVIEW

**Comment by dkiser** [comment]
This implementation does indeed require the `path` to exist in the `upsert` opcode.  However, if we want to be able to `upsert` a non-existing field in the input, we can modify this to support that easily.

File: plugins/logs/mask.go [hunk 1]
```diff
@@ -0,0 +1,234 @@
...
+		Path:           path,
+		Value:          val,
+		unEscapedParts: unEscapedParts,
+		escapedParts:   escapedParts,
+	}
+
+	return rule, nil
+}
+
+func (r maskRule) Erase(event *EventV1) {
```
Comment (patrick-east) [inline plugins/logs/mask.go:71]: Do we still need to call it `Erase`? Could we make this new one `Mask` or `Apply` or something?

File: plugins/logs/mask.go [hunk 2]
```diff
@@ -0,0 +1,234 @@
...
+
+	if parts[0] != "input" && parts[0] != "result" {
+		return rule, fmt.Errorf("mask prefix not allowed")
+	}
+
+	unEscapedParts := make([]string, len(parts))
+	escapedParts := make([]string, len(parts))
+	for i := range parts {
+		var err error
+		unEscapedParts[i], err = url.QueryUnescape(parts[i])
```
Comment (patrick-east) [inline plugins/logs/mask.go:52]: Why do we need to keep the unescaped parts?

File: plugins/logs/mask.go [hunk 3]
```diff
@@ -0,0 +1,234 @@
...
+				event.Input = nil
+				event.Erased = append(event.Erased, r.String())
+
+			case maskOPUpsert:
+				event.Input = &r.Value
+				event.Masked = append(event.Masked, r.String())
+
+			default:
+				// TODO(dkiser) Do we want to panic instead of return errors here?
+				panic(fmt.Sprintf("illegal mask op value: %s", r.OP))
```
Comment (patrick-east) [inline plugins/logs/mask.go:87]: Lets have this return an error up to the logger plugin, the plugin may or may not be able to do anything other than log an error but its better than a panic. That goes for all of the panics in here.

File: plugins/logs/mask_test.go [hunk 4]
```diff
@@ -0,0 +1,482 @@
...
+				Path:           "/input",
+				escapedParts:   []string{"input"},
+				unEscapedParts: []string{"input"},
+			},
+		},
+	}
+
+	for _, tc := range tests {
+		t.Run(tc.note, func(t *testing.T) {
+			// result, err := parsePtr(tc.input)
```
Comment (patrick-east) [inline plugins/logs/mask_test.go:131]: nit: Please remove commented out code

File: plugins/logs/mask_test.go [hunk 5]
```diff
@@ -0,0 +1,482 @@
...
+				}
+				if !reflect.DeepEqual(result, tc.expPtr) {
+					t.Fatalf("Expected %#+v but got %#+v", tc.expPtr, result)
+				}
+			}
+		})
+	}
+}
+
+func TestMaksRuleErase(t *testing.T) {
```
Comment (patrick-east) [inline plugins/logs/mask_test.go:151]: nit: typo `TestMaksRuleErase` -> `TestMaskRuleErase`

File: plugins/logs/plugin_test.go [hunk 6]
```diff
@@ -483,152 +483,240 @@ func TestPluginReconfigure(t *testing.T) {
...
+				"is_sensitive": true,
+			},
+			reconfigure: true,
+		},
+		{
+			note: "simple upsert (with body true)",
+			rawPolicy: []byte(`
+				package system.log
+				mask[{"op": "upsert", "path": "/input/password", "value": x}] {
+					# logic to compute signature value
```
Comment (patrick-east) [inline plugins/logs/plugin_test.go:533]: Is this comment supposed to be in the policy snippet?

File: docs/content/management.md [hunk 7]
```diff
@@ -426,6 +425,50 @@ There are a few restrictions on the JSON Pointers that OPA will erase:
...
+package system.log
+
+# op: opcode for the mask operation (upsert|remove)
+# path: the full document object path to perform operation against
+# value: a variable that will be set from evaluating the mask body
+#        (this is processed for every decision being logged, so
+#         be mindful of performance when performing complex
+#         opertions in the mask body, such as crypto opertions)
+mask[{"op": "upsert", "path": "/input/password", "value": x}] {
+  input.input.password
```
[the remark this answers is not in the document]
Comment (dkiser) [reply docs/content/management.md:443]: @patrick-east See last commit update and let me know what you think!

File: plugins/logs/mask.go [hunk 8]
```diff
@@ -0,0 +1,234 @@
+package logs
```
[the remark this answers is not in the document]
Comment (dkiser) [reply plugins/logs/mask.go:5]: Fixed in last commit.

File: docs/content/management.md [hunk 9]
```diff
@@ -426,6 +425,50 @@ There are a few restrictions on the JSON Pointers that OPA will erase:
 * Pointers must refer to object keys. Pointers to array elements will be treated
   as undefined. For example `/input/emails/0/value` is allowed but `/input/emails/0` is not.
 
+In order to **modify** the contents of an input field, the **mask** synax has been
+enhanced to support the following optional format.
```
[the remark this answers is not in the document]
Comment (dkiser) [reply docs/content/management.md]: See last commit and let me know what you think.

File: docs/content/management.md (hunk 7 above)
[the remark this answers is not in the document]
Comment (dkiser) [reply docs/content/management.md:443]: See last commit.

File: plugins/logs/mask.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (dkiser) [reply plugins/logs/mask.go:5]: Updated in last commit.

File: plugins/logs/mask.go (hunk 2 above)
Comment (dkiser) [reply plugins/logs/mask.go]: Cleaned this up.

File: docs/content/management.md [hunk 10]
```diff
@@ -426,6 +425,64 @@ There are a few restrictions on the JSON Pointers that OPA will erase:
 * Pointers must refer to object keys. Pointers to array elements will be treated
   as undefined. For example `/input/emails/0/value` is allowed but `/input/emails/0` is not.
 
+In order to **modify** the contents of an input field, the **mask** rule may utilize the following format.
+The structured rule format below provides the ability to choose an opcode for the operation and a value to
+upsert.  If an opcode of **remove** is provided, the value field will be ignored.
```
[the remark this answers is not in the document]
Comment (dkiser) [reply docs/content/management.md:430]: Sounds good, will work on that when get some minutes.

File: plugins/logs/mask.go [hunk 11]
```diff
@@ -0,0 +1,236 @@
...
+func (r maskRule) String() string {
+	return "/" + strings.Join(r.escapedParts, "/")
+}
+
+func newMaskRule(op maskOP, path string, val interface{}) (maskRule, error) {
+	rule := maskRule{}
+
+	if len(path) == 0 {
+		return rule, fmt.Errorf("mask must be non-empty")
+	} else if path[0] != '/' {
```
Comment (ashutosh-narkar) [inline plugins/logs/mask.go:41]: nit: use `strings.HasPrefix`

File: plugins/logs/mask.go [hunk 12]
```diff
@@ -0,0 +1,236 @@
...
+
+			case maskOPUpsert:
+				event.Result = &r.Value
+				event.Masked = append(event.Masked, r.String())
+
+			default:
+				return fmt.Errorf("illegal mask op value: %s", r.OP)
+			}
+		default:
+			return fmt.Errorf("illegal path value value: %s", p)
```
Comment (ashutosh-narkar) [inline plugins/logs/mask.go:103]: Nit: duplicate `value`

File: plugins/logs/mask.go [hunk 13]
```diff
@@ -0,0 +1,236 @@
...
+	}
+
+	return rule, nil
+}
+
+func (r maskRule) Mask(event *EventV1) error {
+
+	if len(r.escapedParts) == 1 {
+		switch p := r.escapedParts[0]; p {
+		case "input":
```
Comment (ashutosh-narkar) [inline plugins/logs/mask.go:75]: We can probably move the common code below into a function.

File: plugins/logs/mask.go [hunk 14]
```diff
@@ -0,0 +1,236 @@
...
+			event.Erased = append(event.Erased, r.String())
+
+		case maskOPUpsert:
+
+			inputObj, ok := node.(map[string]interface{})
+			if !ok {
+				return nil
+			}
+
+			delete(inputObj, fld)
```
Comment (ashutosh-narkar) [inline plugins/logs/mask.go:145]: Is the delete statement needed if we are overwriting below ?

File: plugins/logs/mask.go [hunk 15]
```diff
@@ -0,0 +1,236 @@
...
+			rule, err = newMaskRule(rule.OP, rule.Path, rule.Value)
+			if err != nil {
+				return nil, err
+			}
+
+			mRules = append(mRules, rule)
+
+		default:
+			return nil, fmt.Errorf("invalid mask rule format encountered: %s", reflect.TypeOf(v).String())
+		}
```
Comment (ashutosh-narkar) [inline plugins/logs/mask.go:232]: Nit:
```golang
return nil, fmt.Errorf("invalid mask rule format encountered: %T", v)
```

File: plugins/logs/mask.go [hunk 16]
```diff
@@ -0,0 +1,236 @@
...
+	if len(path) == 0 {
+		return rule, fmt.Errorf("mask must be non-empty")
+	} else if path[0] != '/' {
+		return rule, fmt.Errorf("mask must be slash-prefixed")
+	}
+
+	parts := strings.Split(path[1:], "/")
+
+	if parts[0] != "input" && parts[0] != "result" {
+		return rule, fmt.Errorf("mask prefix not allowed")
```
Comment (ashutosh-narkar) [inline plugins/logs/mask.go:48]: Nit: 
```go
fmt.Errorf("mask prefix not allowed: %v", parts[0]) 
```

File: plugins/logs/mask_test.go [hunk 17]
```diff
@@ -0,0 +1,489 @@
...
+				Path: "/input/foo/bar/baz",
+			},
+			event: `{"input": {"foo": {}}}`,
+			exp:   `{"input": {"foo": {}}}`,
+		},
+		{
+			note: "upsert: undefined object: missing key",
+			ptr: maskRule{
+				OP:   maskOPUpsert,
+				Path: "/input/foo/bar/baz",
```
Comment (ashutosh-narkar) [inline plugins/logs/mask_test.go:291]: If we had provided a value, would this create an entry in the modified input ?

Comment (dkiser) [reply plugins/logs/mask_test.go:291]: It would not, since the fully qualified json. pointer to `"/input/foo/bar/baz"` does not exist.

File: plugins/logs/mask.go (hunk 14 above)
Comment (dkiser) [reply plugins/logs/mask.go:145]: It is not, will remove.

File: docs/content/management.md [hunk 18]
```diff
@@ -426,6 +425,64 @@ There are a few restrictions on the JSON Pointers that OPA will erase:
...
+  "erased": [
+    "/input/ssn"
+  ],
+  "masked": [
+    "/input/password"
+  ],
+  "input": {
+    "name": "bob",
+    "resource": "user",
+    "password":"**REDACTED**"
```
Comment (tsandall) [inline docs/content/management.md:476]: nit: missing space between "password": and "**REDACTED**"

File: plugins/logs/mask.go [hunk 19]
```diff
@@ -0,0 +1,236 @@
...
+			}
+		case "result":
+			if event.Result != nil {
+				node = *event.Result
+			}
+		default:
+			return fmt.Errorf("illegal path value value: %s", p)
+		}
+
+		parent := r.lookup(r.escapedParts[1:len(r.escapedParts)-1], node)
```
Comment (tsandall) [inline plugins/logs/mask.go:121]: @dkiser the only important comment I have right now is that we should make upsert create intermediate nodes as necessary (like `mkdir -p`). The reason is that otherwise users aren't going to be able to do so reliably because:

* Each mask rule can only generate one operation
* Mask rules are generating a set of operations which are unordered

We could make each make rule generate multiple operations however it'll be somewhat complicated for policies to generate the set of upsert (or other operation types) required to create the hierarchy.

Having the upsert operation create the intermediate nodes resolves these problems.

Comment (dkiser) [reply plugins/logs/mask.go:121]: @tsandall  - How should we treat paths with an array index?  Should we ignore these and only allow upsert of objects?

I'll have to mull over how to dynamically created the intermediate nodes.

Comment (tsandall) [reply plugins/logs/mask.go:120]: Let's just assume objects for now.

As far as how to create the nodes, here's some code (warning, I haven't tested it):

```golang
func mkdirp(node map[string]interface{}, path []string, value interface{}) bool {
  if len(path) == 0 { return false }
  for i := 0; i < len(path)-1; i++ {
    child, ok := node[path[i]]
    if !ok {
      child := map[string]interface{}{}
      node[path[i]] = child
      node = child
    } else if asobj, ok := child.(map[string]interface{}); ok {
       node = asob
    } else {
      return false
   }
  }
  node[path[len(path)-1]] = value
  return true
}
```

Comment (dkiser) [reply plugins/logs/mask.go:120]: Thanks! Playing with these ideas now.

File: plugins/logs/mask.go (hunk 13 above)
Comment (dkiser) [reply plugins/logs/mask.go]: Refactored the Mask function.

File: plugins/logs/mask.go (hunk 19 above)
Comment (dkiser) [reply plugins/logs/mask.go]: @tsandall Added a similar method.  It does make we wonder if we handle `[]interface{}` here as well.

**Comment by tsandall** [comment]
@dkiser thanks for adding the upsert support! I tried it out this morning and it works nicely. We should adjust some of the error handling though IMO.

1. The decision logger should validate as much of the mask instructions as possible in one shot and generate an error if any validation issues are found. Let's make the `op` validation happen inside `newMaskRule`. This way if the `op` is missing or incorrect and OPA cannot tell what to do with it, it will be caught.

2. The decision logger should treat undefined paths consistently for remove and upsert operations. Currently if the upsert specifies an undefined path, e.g., a reference into an array, the decision logger reports an error. I think we should suppress these.

Re: (2), I could imagine some users wanting OPA to fail if the path is undefined. I think we can add support for this later if necesarry, either via config or by extending the instructions.

**Comment by tsandall** [comment]
@dkiser let us know if you can work on those remaining comments around error handling in the next week or so. If not, we can take on those changes so that this lands in the next release.

**Comment by dkiser** [comment]
@tsandall I'll find some time over the next couple of days and see about addressing those last two comments.  Thanks!

**Comment by dkiser** [comment]
> @dkiser thanks for adding the upsert support! I tried it out this morning and it works nicely. We should adjust some of the error handling though IMO.
> 
> 1. The decision logger should validate as much of the mask instructions as possible in one shot and generate an error if any validation issues are found. Let's make the `op` validation happen inside `newMaskRule`. This way if the `op` is missing or incorrect and OPA cannot tell what to do with it, it will be caught.
> 2. The decision logger should treat undefined paths consistently for remove and upsert operations. Currently if the upsert specifies an undefined path, e.g., a reference into an array, the decision logger reports an error. I think we should suppress these.
> 
> Re: (2), I could imagine some users wanting OPA to fail if the path is undefined. I think we can add support for this later if necesarry, either via config or by extending the instructions.

@tsandall Re: (2), Do we mean that an upsert to an undefined path for an undefined object type to fail silently?  I think we want to keep the ability to upsert to an undefined path for a defined upsert object type, which right now it just a `map[string]interface{}`?  

Do you have an existing unit test case to point to that behavior should be changed on?

**Comment by tsandall** [comment]
@dkiser you're right. The term _undefined_ is not accurate here. I'm referring to this line: https://github.com/open-policy-agent/opa/pull/2433/files#diff-dee023b2dcf1c8c236bac28d4d4fd7b8R189.

In the upsert implementation, if the path refers to a non-object intermediate value, it will result in an error being logged. OTOH, in the remove implementation, if the path refers to a non-object intermediate value, it's treated as undefined and ignored. The behaviour should be consistent. I suggest we remove that error and simply treat the upsert as undefined in this case.

**Comment by dkiser** [comment]
@tsandall Can you take a gander at the last commit.  I agree with the configurable option for undefined object path handling (silent or some kind of decision log error) and added low level error handling for this in the mask rule that can be used in a later PR at the `plugin.go` level (left a TODO comment in there).  

Let me know if this new commit addresses your concerns.  Thanks!
