### PR TITLE
Ensure http.send caching works in system.authz

### LINKED ISSUE #3946: http.send caching doesn't work in system.authz policies
## Expected Behavior

`http.send` with `force_cache: true` to cache responses when used in a `system.authz` policy.

## Actual Behavior

No caching seems to be done.

## Steps to Reproduce the Problem

1. Set up a server that responds with a static JSON response, like `{"status": "OK"}` and logs each request.
2. Create a `system.authz` policy.
```rego
package system.authz

default allow = false

allow {
    http.send({
        "url": "http://localhost:8000",
        "method": "GET",
        "force_cache": true,
        "force_cache_duration_seconds": 3600
    }).body.status == "OK"
}
```
3. Start OPA with authz policy configured `opa run --server --authorization=basic --authentication=token`
4. Query OPA a couple of times and see how the HTTP server set up in step 1 logs one request per policy invocation (i,.e. no cache).

If the policy is renamed and used as a normal policy, `http.send` caching works as expected.

Originally reported on Slack by @amrap030

### PR DESCRIPTION
**Pull request by anderseknert**
Fixes #3946

Signed-off-by: Anders Eknert <anders@eknert.com>

### CODE REVIEW

File: server/authorizer/authorizer_test.go [hunk 1]
```diff
@@ -455,6 +457,64 @@ func TestMakeInputWithBody(t *testing.T) {
 
 }
 
+func TestInterQueryCache(t *testing.T) {
+
+	count := 0
+	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+		w.WriteHeader(http.StatusOK)
+		count += 1
```
Comment (srenatus) [inline server/authorizer/authorizer_test.go:465]: [nit]
```suggestion
		count++
```

**Review by srenatus — APPROVED** [review]

File: server/authorizer/authorizer_test.go (hunk 1 above)
Comment (anderseknert) [reply server/authorizer/authorizer_test.go:465]: Hehe, context switching from Python does that I guess :D

**Review by srenatus — APPROVED** [review]
