### PR TITLE
ast/compile: fix print rewriting for arrays in unification

### LINKED ISSUE #4078: print fails for variables assigned in destructured array
OPA print function fails when printing variable assigned in destructured array.

* OPA version: 0.34.2/HEAD@main
* Example policy: 
```rego
package example

jwt := "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"

test = payload {
    [_, payload, _] := io.jwt.decode(jwt)
    print(payload)
}
```
* Example CLI command: `opa eval -d <broken.rego> "data.example.test"`
* Example output that OPA returned: 
```json
{
  "errors": [
    {
      "message": "var __local1__ is undeclared",
      "code": "rego_compile_error",
      "location": {
        "file": "broken.rego",
        "row": 7,
        "col": 11
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by srenatus**
outputVarsForExprEq, which is used in the rewriting of `print()` calls,
wasn't able to find `x` in

    [_, x, _] = f(1)

and thus certain print expressions failed during the rewriting stage of
print() calls in the compiler.

Now, the "collection (array/object) = func call" is handled.

Furthermore, this adds calls to isRefSafe in a few places: as it turned
out, the test cases

    {"array/ref", "[1,2,x] = a[_]", "[a]", "[x]"},
    {"object/ref", `{"x": x} = a[_]`, "[a]", "[x]"},

would have, without the check, passed without "a" in "safe" (3rd field).
The fact that these cases are including "a" is evidence for this being
the correct behaviour.

Fixes #4078.

### CODE REVIEW

File: ast/unify_test.go [hunk 1]
```diff
@@ -31,7 +31,14 @@ func TestUnify(t *testing.T) {
 		{"object/var-3", `{"x": 1, "y": x} = y`, "[]", "[]"},
 		{"object/uneven", `{"x": x, "y": 1} = {"x": y}`, "[]", "[]"},
 		{"object/uneven", `{"x": x, "y": 1} = {"x": y}`, "[x]", "[]"},
-		{"call", "x = f(y)[z]", "[y]", "[x]"},
+		{"var/call-ref", "x = f(y)[z]", "[y]", "[x]"},
```
Comment (tsandall) [inline ast/unify_test.go:34]: nit: I could imagine adding negative cases where one or more of the input arguments are not safe and therefore the output should not include any new variables. I'd include cases w/ vars as args as well as arrays/sets/objects containing vars.

**Review by tsandall — DISMISSED** [review]
LGTM. I think there's room for a small improvement on the unify test cases.

File: ast/unify.go [hunk 2]
```diff
@@ -67,6 +71,10 @@ func (u *unifier) unify(a *Term, b *Term) {
 			if isRefSafe(b, u.safe) {
 				u.markSafe(a)
 			}
+		case Call:
+			if isCallSafe(b, u.safe) {
+				u.markSafe(a)
+			}
```
Comment (srenatus) [inline ast/unify.go:77]: 💡 Found this when adding extra negative test cases.
