### PR TITLE
wasm_sdk: use context, enable and use interrupts 

### LINKED ISSUE #3212: rego.Eval with wasm target doesn't respect context
## Expected Behavior

The test added in https://github.com/open-policy-agent/opa/pull/3211 **passes**.

## Actual Behavior

For the wasm target, it does not pass. Instead, the long-running policy is fully evaluated, which takes around 80s on my machine.

## Steps to Reproduce the Problem

With the linked PR's branch checked out, run its test:

```
$ go test -mod=vendor -tags opa_wasm ./rego -run TestEvalWithContextTimeout/rego -v
=== RUN   TestEvalWithContextTimeout
=== RUN   TestEvalWithContextTimeout/rego
--- PASS: TestEvalWithContextTimeout (0.20s)
    --- PASS: TestEvalWithContextTimeout/rego (0.20s)
PASS
ok      github.com/open-policy-agent/opa/rego   0.222s

$ go test -mod=vendor -tags opa_wasm ./rego -run TestEvalWithContextTimeout/wasm -v
=== RUN   TestEvalWithContextTimeout
=== RUN   TestEvalWithContextTimeout/wasm
FAIL    github.com/open-policy-agent/opa/rego   82.010s
FAIL

$
```

### Notes

[`InterruptHandle`](https://pkg.go.dev/github.com/bytecodealliance/wasmtime-go#InterruptHandle) seems to be what we'd use to fix this.

### PR DESCRIPTION
**Pull request by srenatus**
All in all, there's three cases where cancellation is somewhat interesting:

- native functions: `numbers.range`
- host functions using topdown.Cancel: `net.cidr_expand`
- host functions using context.Context: `http.send`

The tests also pin down the behaviour of these three cases in topdown eval.
There, the numbers.range and net.cidr_expand cases _should_ be the same,
but as it turns out, the former didn't check for cancellation.

This is also fixed here.

The comparison of the `wasmtime.Trap`'s `Message()` using `strings.HasPrefix`
is not great, but gets the job done for now. (👉 https://github.com/bytecodealliance/wasmtime-go/issues/63)

:warning: Something is still flaky here, I've seen this once during my iterations:

    === RUN   TestEvalWithContextTimeout/wasm/net.cidr_expand
        rego_wasmtarget_test.go:209: failed checking error, got context deadline exceeded (context.deadlineExceededError)

☝️ This happens when the tests fail to acquire a vm before the context times out. It was happening a lot when running in github actions, so I've increased the deadline to 1s.

--------
There is some inherent race condition here: the context could be cancelled
when the Eval() function has already stopped calling into the VM. We then
set a trap, and the next call into the wasm instance will be interrupted.
To avoid that, we're "clearing interrupts" at the beginning of every call
path that leads into one or more wasm instance function calls. This is a
price to pay, but I couldn't find any robust solution to avoid the
problematic scenario.

-------

Fixes #3212.

### CODE REVIEW

File: rego/rego_test.go [hunk 1]
```diff
@@ -1735,6 +1735,38 @@ func TestPrepareWithWasmTargetNotSupported(t *testing.T) {
...
+			).PrepareForEval(ctx)
+			if err != nil {
+				t.Fatal(err)
+			}
+
+			_, err = pq.Eval(ctx)
+			if err == nil {
+				t.Fatal("expected err, got nit")
+			}
+			if !topdown.IsCancel(err) {
```
Comment (srenatus) [inline rego/rego_test.go:1763]: ⚠️ For the wasm target, this won't be true either -- it'll return a different error. But it should _never_ run until completion and return `nil`.

**Comment by tsandall** [comment]
Can we set the context on the `builtinDispatcher` instance inside of the VM's `Eval` function? This would let us propagate the context into the built-in functions implemented in Go.

File: rego/rego_wasmtarget_test.go [hunk 2]
```diff
@@ -89,3 +97,122 @@ func TestPrepareAndEvalWithWasmTargetModulesOnCompiler(t *testing.T) {
...
+	// Also a host functiopn, but uses context.Context for cancellation.
+	httpSend := fmt.Sprintf(`package p
+allow {
+	http.send({"method": "get", "url": "%s", "raise_error": true})
+}`,
+		ts.URL)
+	httpSendTopdownError := fmt.Sprintf(`http.send: Get "%s": context deadline exceeded`, ts.URL)
+
+	// This is a natively-implemented function that just takes long.
+	// NOTE(sr): On my machine, it starts exceeding 200ms when passed 1e6,
```
Comment (srenatus) [inline rego/rego_wasmtarget_test.go:132]: This comment is from a time when I hadn't adjusted the timeout to work with CI. I'll drop it before merging.

File: internal/wasm/sdk/opa/errors/errors.go [hunk 3]
```diff
@@ -23,4 +23,6 @@ var (
 	ErrNonBoolean = errors.New("non-boolean decision")
 	// ErrInternal is the error returned if the evaluation fails due to an internal error.
 	ErrInternal = errors.New("internal error")
+	// ErrCancelled is the error returned if the evaluation is cancelled.
+	ErrCancelled = errors.New("cancelled")
```
Comment (tsandall) [inline internal/wasm/sdk/opa/errors/errors.go:27]: I noticed these errors make it all the way out to the user. It would be nice to (eventually, not in this PR) unify them a bit w/ the errors from topdown:

```
(sr/wasm/context)torin:~/go/src/github.com/open-policy-agent/opa$ ./opa_linux_amd64 test --timeout=1s ~/x.rego -v
data.x.test_xxx: ERROR (1.0009364s)
  eval_cancel_error: numbers.range: timed out before generating all numbers in range
--------------------------------------------------------------------------------
ERROR: 1/1
(sr/wasm/context)torin:~/go/src/github.com/open-policy-agent/opa$ ./opa_linux_amd64 test --timeout=1s ~/x.rego -t wasm
data.x.test_xxx: ERROR (1.0010134s)
  cancelled
--------------------------------------------------------------------------------
ERROR: 1/1
```

**Review by tsandall — DISMISSED** [review]
I've read through the changes and exercised the timeout via `opa test`. LGTM.

File: internal/wasm/sdk/opa/errors/errors.go (hunk 3 above)
Comment (srenatus) [reply internal/wasm/sdk/opa/errors/errors.go:27]: Definitely! I'll create an issue to track this.

File: go.mod [hunk 4]
```diff
@@ -1,11 +1,12 @@
 module github.com/open-policy-agent/opa
 
-go 1.12
+go 1.15
```
[the remark this answers is not in the document]
Comment (srenatus) [reply go.mod:3]: Decided against doing this so underhandedly. I'll change this in a follow-up, I think we could the same thing recently introduced in opa-envoy-plugin (https://github.com/open-policy-agent/opa-envoy-plugin/pull/238) in here. But not now 😄

File: internal/wasm/sdk/opa/errors/errors.go (hunk 3 above)
Comment (srenatus) [reply internal/wasm/sdk/opa/errors/errors.go:27]: OK I didn't exactly cover myself in glory with the issue, but here it is: https://github.com/open-policy-agent/opa/issues/3225

File: internal/wasm/sdk/internal/wasm/vm.go [hunk 5]
```diff
@@ -581,3 +626,23 @@ func callVoid(vm *VM, name string, args ...int32) error {
 	_, err := vm.instance.GetExport(name).Func().Call(sl...)
 	return err
 }
+
+func (i *VM) clearInterrupts(ctx context.Context) error {
```
Comment (srenatus) [inline internal/wasm/sdk/internal/wasm/vm.go:630]: For re-review, please just focus on this: the "clear interrupts" logic added to avoid falling over spurious traps set from previous runs.

Comment (tsandall) [reply internal/wasm/sdk/internal/wasm/vm.go:630]: This seems like a necessary evil. The simplest approach for us would be to only call the interrupt handler if the VM was executing. Unfortunately, the cancellation goroutine has no way of knowing if the VM is executing. This allows the cancellation goroutine to race and call the interrupt handler when it's not necessary.
