### PR TITLE
fix: Fix race condition in json schema parsing with reused references

### LINKED ISSUE #5183: bug: JSON Schemas with recursive and reused elements are not applied correctly
## Short description 

*NOTE: PR incoming!*

Using JSON schemas with recursive elements is still buggy when reusing the same element in multiple locations. This is because the cache key used is unique only to the object in the schema, not the property. This seems to be a side effect of the gojsonschema package. I have a fix for this incoming which is to cache things based on the full reference URL instead of the node id.

## Steps To Reproduce

Use the following schema:
```

  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/aquasecurity/defsec/tree/master/pkg/rego/schemas/cloud.json",
  "type": "object",
  "properties": {
    "aws": {
      "type": "object",
      "$ref": "#/$defs/github.com.aquasecurity.defsec.pkg.providers.aws.AWS"
    }
  },
  "$defs": {
    "github.com.aquasecurity.defsec.pkg.providers.aws.AWS": {
      "type": "object",
      "properties": {
        "iam": {
          "type": "object",
          "$ref": "#/$defs/github.com.aquasecurity.defsec.pkg.providers.aws.iam.IAM"
        },
        "sqs": {
          "type": "object",
          "$ref": "#/$defs/github.com.aquasecurity.defsec.pkg.providers.aws.sqs.SQS"
        }
      }
    },
    "github.com.aquasecurity.defsec.pkg.providers.aws.iam.Document": {
      "type": "object"
    },
    "github.com.aquasecurity.defsec.pkg.providers.aws.iam.IAM": {
      "type": "object",
      "properties": {
        "policies": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/$defs/github.com.aquasecurity.defsec.pkg.providers.aws.iam.Policy"
          }
        }
      }
    },
    "github.com.aquasecurity.defsec.pkg.providers.aws.iam.Policy": {
      "type": "object",
      "properties": {
        "builtin": {
          "type": "object",
          "properties": {
            "value": {
              "type": "boolean"
            }
          }
        },
        "document": {
          "type": "object",
          "$ref": "#/$defs/github.com.aquasecurity.defsec.pkg.providers.aws.iam.Document"
        }
      }
    },
    "github.com.aquasecurity.defsec.pkg.providers.aws.sqs.Queue": {
      "type": "object",
      "properties": {
        "policies": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/$defs/github.com.aquasecurity.defsec.pkg.providers.aws.iam.Policy"
          }
        }
      }
    },
    "github.com.aquasecurity.defsec.pkg.providers.aws.sqs.SQS": {
      "type": "object",
      "properties": {
        "queues": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/$defs/github.com.aquasecurity.defsec.pkg.providers.aws.sqs.Queue"
          }
        }
      }
    }
  }
}
```

Try to validate the following policy document with it:

```
# METADATA
# schemas:
#  - input: schema.input
package race.condition

deny {
	queue := input.aws.sqs.queues[_]
	policy := queue.policies[_]
	doc := json.unmarshal(policy.document.value)
	statement = doc.Statement[_]
	action := statement.Action[_]
	action == "*"
}
```

## Expected behavior
It should tell us the module is valid 100% of the time - but you can observe that sometimes the validation fails and expects recursive elements e.g. `input.aws.sqs.sqs` instead of `input.aws.sqs.queues`

### PR DESCRIPTION
**Pull request by liamg**
Resolves #5183 

Signed-off-by: Liam Galvin <liam.galvin@aquasec.com>

### CODE REVIEW

File: ast/compile_test.go [hunk 1]
```diff
@@ -7454,3 +7454,119 @@ deny {
 	}
 
 }
+
+func TestCompilerWithRecursiveSchemaAvoidRace(t *testing.T) {
+
+	jsonSchema := `{
+  "$schema": "https://json-schema.org/draft/2020-12/schema",
+  "$id": "https://github.com/aquasecurity/defsec/tree/master/pkg/rego/schemas/cloud.json",
```
Comment (srenatus) [inline ast/compile_test.go:7462]: [nit] This 404s. it's probably not relevant, but could we just put something example.com-y in here? (also below, `s/github.com.aquasecurity.defsec/example.com.thingy/`)

File: ast/compile.go [hunk 2]
```diff
@@ -1067,18 +1067,18 @@ func newSchemaParser() *schemaParser {
 	}
 }
 
-func (parser *schemaParser) parseSchema(schema interface{}) (types.Type, error) {
```
Comment (srenatus) [inline ast/compile.go:1070]: [nit] Since most callers don't need the `propertyKey`, can we do

```go
func (parser *schemaParser) parseSchema(schema interface{}) (types.Type, error) {
  return p.parseSchemaWithPropertyKey(schema, "")
}

func (parser *schemaParser) parseSchema(schema interface{}, propertyKey string) (types.Type, error) {
    // ... 
}
```
? 🤔

**Review by srenatus — APPROVED** [review]
Thanks! Nitpicks only.

**Review by srenatus — APPROVED** [review]
nice and tidy. thanks! 😃
