### PR TITLE
fmt: report wrong arity for built-in functions

### LINKED ISSUE #5646: fmt: panic on type error
An edge case for sure, but `opa fmt` panics on cerrtain invalid constructs, like this example.

```rego
package play

test_and_false_false {
	and([true, false]) == false
}
```

```
❯ opa fmt .
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/open-policy-agent/opa/format.(*writer).writeCall(0x14000123a40, 0x0, {0x140002f2cf0?, 0x2, 0x2}, {0x0, 0x0, 0x0})
	/Users/anderseknert/git/opa/opa/format/format.go:781 +0x248
github.com/open-policy-agent/opa/format.(*writer).writeTermParens(0x14000123a40, 0x0?, 0x1400026bd10, {0x0?, 0x140003bf248?, 0x102dbb7ac?})
	/Users/anderseknert/git/opa/opa/format/format.go:711 +0x2b8
github.com/open-policy-agent/opa/format.(*writer).writeTerm(...)
	/Users/anderseknert/git/opa/opa/format/format.go:676
github.com/open-policy-agent/opa/format.(*writer).writeFunctionCall(0x14000123a40, 0x0?, {0x0, 0x0, 0x0})
	/Users/anderseknert/git/opa/opa/format/format.go:638 +0x2bc
github.com/open-policy-agent/opa/format.(*writer).writeExpr(0x14000123a40, 0x140001aef40, {0x0?, 0x0?, 0x140001aec00?})
	/Users/anderseknert/git/opa/opa/format/format.go:541 +0x108
github.com/open-policy-agent/opa/format.(*writer).writeBody(0x14000123a40?, {0x140005d84b8, 0x1, 0x0?}, {0x0?, 0x0?, 0x10403a520?})
	/Users/anderseknert/git/opa/opa/format/format.go:519 +0x80
github.com/open-policy-agent/opa/format.(*writer).writeRule(0x14000123a40, 0x140001aef00, 0x0?, {0x0?, 0x0?, 0x0?}, {0x0, 0x0, 0x0})
	/Users/anderseknert/git/opa/opa/format/format.go:358 +0x3bc
github.com/open-policy-agent/opa/format.(*writer).writeRules(0x10378dca0?, {0x140005d84f0, 0x1, 0x0?}, {0x0?, 0x0?, 0x0?}, {0x0?, 0x10460c108?, 0x12bc4db98?})
	/Users/anderseknert/git/opa/opa/format/format.go:305 +0x84
github.com/open-policy-agent/opa/format.(*writer).writeModule(0x14000123a40, 0x1400049b180?, {0x0?, 0xec?, 0x27?})
	/Users/anderseknert/git/opa/opa/format/format.go:272 +0x3e8
github.com/open-policy-agent/opa/format.AstWithOpts({0x103737020?, 0x1400049b100?}, {0x40?})
	/Users/anderseknert/git/opa/opa/format/format.go:152 +0x590
github.com/open-policy-agent/opa/format.Ast(...)
	/Users/anderseknert/git/opa/opa/format/format.go:61
github.com/open-policy-agent/opa/format.Source({0x140001e9f30, 0xb}, {0x14000228800?, 0x1027e4714?, 0x140003bf898?})
	/Users/anderseknert/git/opa/opa/format/format.go:40 +0xc8
github.com/open-policy-agent/opa/cmd.formatFile(0x104075058, {0x103822260, 0x14000120008}, {0x140001e9f30, 0xb}, {0x10382e6c8, 0x1400011f450}, {0x0?, 0x0?})
	/Users/anderseknert/git/opa/opa/cmd/fmt.go:111 +0x1d4
github.com/open-policy-agent/opa/cmd.opaFmt.func1({0x140001e9f30?, 0x0?}, {0x10382e6c8?, 0x1400011f450?}, {0x0?, 0x0?})
	/Users/anderseknert/git/opa/opa/cmd/fmt.go:76 +0x68
path/filepath.walk({0x140001e9f30, 0xb}, {0x10382e6c8, 0x1400011f450}, 0x103819748)
	/opt/homebrew/Cellar/go/1.19.4/libexec/src/path/filepath/path.go:433 +0xd0
path/filepath.walk({0x16d6835f8, 0x1}, {0x10382e6c8, 0x1400011f380}, 0x103819748)
	/opt/homebrew/Cellar/go/1.19.4/libexec/src/path/filepath/path.go:457 +0x1fc
path/filepath.Walk({0x16d6835f8, 0x1}, 0x103819748)
	/opt/homebrew/Cellar/go/1.19.4/libexec/src/path/filepath/path.go:520 +0x6c
github.com/open-policy-agent/opa/cmd.opaFmt({0x140002f2bc0?, 0x1, 0x0?})
	/Users/anderseknert/git/opa/opa/cmd/fmt.go:75 +0xe4
github.com/open-policy-agent/opa/cmd.glob..func1(0x104020d60?, {0x140002f2bc0?, 0x1?, 0x1?})
	/Users/anderseknert/git/opa/opa/cmd/fmt.go:53 +0x2c
github.com/spf13/cobra.(*Command).execute(0x104020d60, {0x140002f2b80, 0x1, 0x1})
	/Users/anderseknert/git/opa/opa/vendor/github.com/spf13/cobra/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x104020a80)
	/Users/anderseknert/git/opa/opa/vendor/github.com/spf13/cobra/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/anderseknert/git/opa/opa/vendor/github.com/spf13/cobra/command.go:968
main.main()
	/Users/anderseknert/git/opa/opa/main.go:14 +0x28
```

Originally reported by @nevumx.

### PR DESCRIPTION
**Pull request by Trolloldem**
This PR fixes #5646. As discussed in the issue, `opa fmt` crashes when  a built-in function with a corresponding `Infix` is processed by the [writeCall](https://github.com/open-policy-agent/opa/blob/main/format/format.go#L763) function. This is due to the fact that, previously to this PR, this function assumed that the number of arguments provided is exactly the expected number. Due to this assumption, when these functions are processed in `writeCall` with only one argument, `opa fmt` panics due to an unhandled `index out of range` error.

As noted in #5646, this is not the only issue caused by the assumption used in `writeCall`. Currently, if the number of arguments provided to built-in functions with a corresponding `Infix` is larger than the expected number, only the first two are processed, while the other are simple removed from formatted document.

This error is visible only when the function is used as a term of another function (`writeCall` is used only in [writeTermParens](https://github.com/open-policy-agent/opa/blob/main/format/format.go#L679)). 
Normally a function is processed by [writeFunctionCall](https://github.com/open-policy-agent/opa/blob/main/format/format.go#L618), which delegates the process to [writeFunctionCallPlain](https://github.com/open-policy-agent/opa/blob/main/format/format.go#L653) in case of wrong arity.

Since both the `assignment` and the `equality` operator are treated as built-in functions, the check `and([true, false]) == false` causes the call `and([true, false])` to be processed as a term. This leads to the panic noted in #5646.

To fix this behavior, this PR introduces arity checks for built-in functions and introduces error handling for panics that can be found during the execution of `opa fmt`. The changes are the following:

- [arity check](https://github.com/Trolloldem/opa/blob/5bcc2287f9b783287afe9bf6b76bbb718993c47b/format/format.go#L795) in `writeCall` for all the built-in functions with a corresponding `Infix` that are not the `in` operator
- [arity check](https://github.com/Trolloldem/opa/blob/5bcc2287f9b783287afe9bf6b76bbb718993c47b/format/format.go#L811) in `writeInOperator` for the `in` operator
- [slice of errors](https://github.com/Trolloldem/opa/blob/5bcc2287f9b783287afe9bf6b76bbb718993c47b/format/format.go#L150) declared in `AstWithOpts` to collect all the errors found during the format procedure. This behavior is similar to the one obtained through the [Scanner struct](https://github.com/open-policy-agent/opa/blob/main/ast/internal/scanner/scanner.go#L27) used during the parsing procedure
- [Error formatting](https://github.com/Trolloldem/opa/blob/5bcc2287f9b783287afe9bf6b76bbb718993c47b/format/format.go#L1391), similar to the one performed at [compile time](https://github.com/open-policy-agent/opa/blob/main/ast/compile.go#L998)
- [error handling tests](https://github.com/Trolloldem/opa/blob/5bcc2287f9b783287afe9bf6b76bbb718993c47b/cmd/fmt_test.go#L294)

### CODE REVIEW

File: format/format.go [hunk 1]
```diff
@@ -144,40 +147,46 @@ func AstWithOpts(x interface{}, opts Opts) ([]byte, error) {
...
-		w.writeTerm(&ast.Term{Value: x, Location: &ast.Location{}}, nil)
+		w.writeTerm(&ast.Term{Value: x, Location: &ast.Location{}}, nil, &errs)
 	case *ast.Comment:
-		w.writeComments([]*ast.Comment{x})
+		w.writeComments([]*ast.Comment{x}, &errs)
 	default:
 		return nil, fmt.Errorf("not an ast element: %v", x)
 	}
 
+	if len(errs) > 0 {
```
Comment (srenatus) [inline format/format.go:187]: What do you think about adding an `errs` field to `w`? It should be available to all the calls, and we wouldn't need to thread it in. Here, we'd do
```go
if len(w.errs) > 0 {
```

File: format/format.go [hunk 2]
```diff
@@ -1356,3 +1386,36 @@ func ensureFutureKeywordImport(imps []*ast.Import, kw string) []*ast.Import {
...
+	want := make([]string, len(f.Args()))
+	for i := range f.Args() {
+		want[i] = types.Sprint(f.Args()[i])
+	}
+
+	have := make([]string, len(operands))
+	for i := 0; i < len(operands); i++ {
+		have[i] = ast.TypeName(operands[i].Value)
+	}
+	err := ast.NewError(ast.TypeErr, loc, "%v: %v", operator, "arity mismatch")
```
Comment (srenatus) [inline format/format.go:1407]: [nit] it's only strings
```suggestion
	err := ast.NewError(ast.TypeErr, loc, "%s: %s", operator, "arity mismatch")
```

File: cmd/fmt_test.go [hunk 3]
```diff
@@ -269,3 +290,61 @@ func TestFmtFailFileChangesDiff(t *testing.T) {
...
+			policyFile + ":8: rego_type_error: and: arity mismatch",
+			"\thave: (boolean,boolean,boolean)",
+			"\twant: (set[any],set[any])",
+			policyFile + ":9: rego_type_error: plus: arity mismatch",
+			"\thave: (var,var,var,var)",
+			"\twant: (number,number) (2)",
+		}
+		expectedMultipleWrongArityErr := strings.Join(expectedErrLines, "\n")
+
+		if err.Error() != expectedMultipleWrongArityErr {
```
Comment (srenatus) [inline cmd/fmt_test.go:346]: [nit] I'd rather go with an conversion here -- you've introduced an error type, let's use it. 😉 This is easier said then done since it's hidden inside another `ast.NewError`; but if it's possible to get a stricter assertion, that would be nice. What do you think?

File: cmd/fmt_test.go [hunk 4]
```diff
@@ -269,3 +290,61 @@ func TestFmtFailFileChangesDiff(t *testing.T) {
...
+			"\thave: (array)",
+			"\twant: (number,number)",
+			policyFile + ":8: rego_type_error: and: arity mismatch",
+			"\thave: (boolean,boolean,boolean)",
+			"\twant: (set[any],set[any])",
+			policyFile + ":9: rego_type_error: plus: arity mismatch",
+			"\thave: (var,var,var,var)",
+			"\twant: (number,number) (2)",
+		}
+		expectedMultipleWrongArityErr := strings.Join(expectedErrLines, "\n")
```
Comment (srenatus) [inline cmd/fmt_test.go:344]: [style] I'd probably have gone with something like
```go
expectedMultipleWrongArityErr := fmt.Sprintf(`failed to parse Rego source file: %[1]s: 3 errors occurred:
   %[1]s:7: rego_type_error: plus: arity mismatch
...`, policyFile)
```
but that's just a personal preference. This is fine.

File: cmd/fmt_test.go [hunk 5]
```diff
@@ -30,6 +30,27 @@ const unformatted = `
 
 `
 
+const singleWrongArity = `package test
+
+p {
+	a := 1
+	b := 2
+        plus(a, b, c) == 3
```
Comment (srenatus) [inline cmd/fmt_test.go:38]: [nit] indentation seems a bit off

**Review by srenatus — COMMENTED** [review]
What a nice contribution 👏 Thank you!

Some comments inside -- mostly nitpicks. The `errs` thing on `writer` might work out nicely, too, though -- what do you think?

**Comment by Trolloldem** [comment]
Hi @srenatus and thank you for the review and proposed improvements. This week I am not able to work on this, but I will address all the comments as soos as possible!

File: cmd/fmt_test.go (hunk 3 above)
Comment (Trolloldem) [reply cmd/fmt_test.go]: I have substituted the usage of strings with a comparison with an `Error` with `ArityFormatErrDetail`

File: cmd/fmt_test.go (hunk 4 above)
Comment (Trolloldem) [reply cmd/fmt_test.go]: The previous change should address this one as well

File: cmd/fmt_test.go (hunk 5 above)
Comment (Trolloldem) [reply cmd/fmt_test.go]: Now should be fixed

File: format/format.go [hunk 6]
```diff
@@ -999,7 +1028,7 @@ func (w *writer) objectWriter() entryWriter {
 	}
 }
 
-func (w *writer) listWriter() entryWriter {
+func (w *writer) listWriter(errs *ast.Errors) entryWriter {
```
Comment (srenatus) [inline format/format.go:1031]: Is there some tricky scoping reason behind this, so we cannot use `w.errs` (as in other places) with `w.listWriter` and `w.ObjectWriter`?

File: format/format.go [hunk 7]
```diff
@@ -1356,3 +1385,36 @@ func ensureFutureKeywordImport(imps []*ast.Import, kw string) []*ast.Import {
...
+	}
+	return err
+}
+
+// Lines returns the string representation of the detail.
+func (d *ArityFormatErrDetail) Lines() []string {
+	lines := make([]string, 2)
+	lines[0] = "have: " + "(" + strings.Join(d.Have, ",") + ")"
+	lines[1] = "want: " + "(" + strings.Join(d.Want, ",") + ")"
+	return lines
```
Comment (srenatus) [inline format/format.go:1419]: [nit] It doesn't make much of a difference, but you could also do
```suggestion
	return []string{
		"have: " + "(" + strings.Join(d.Have, ",") + ")",
		"want: " + "(" + strings.Join(d.Want, ",") + ")",
	}
```

File: format/format.go (hunk 6 above)
Comment (Trolloldem) [reply format/format.go]: You are right, they are not necessary. I have removed them in the last commit

**Review by srenatus — DISMISSED** [review]
Thanks 🎈

**Comment by ashutosh-narkar** [comment]
@Trolloldem thanks for the contribution. Can you please squash all your commits and also sign off on the changes. We can then get this in. For reference see https://www.openpolicyagent.org/docs/latest/contrib-code/#commit-messages.

**Comment by Trolloldem** [comment]
> @Trolloldem thanks for the contribution. Can you please squash all your commits and also sign off on the changes. We can then get this in. For reference see https://www.openpolicyagent.org/docs/latest/contrib-code/#commit-messages.

@ashutosh-narkar All commits are now squashed in a single one and the sign off check passes. Let me know if anything else is necessary
